# Importing libraries

In [343]:
import numpy as np
import pandas as pd
import os
import csv
import cv2
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score

In [344]:
!pip install opencv-python

# Path of positive and negative images

In [345]:
folder1=r"C:\ICTS\ICTS DATASET\Positive images\Pedestrian_2"
folder2=r"C:\ICTS\ICTS DATASET\Negative_3000"

# Data Pre-processing

# SIFT descriptor

# Class : Pedestrian

In [346]:
i=0
for filename in os.listdir(folder1):
    #path
    try:
        path=os.path.join(folder1,filename)
        a=cv2.imread(path)

        #resize image
        resize=(180,230)
        img=cv2.resize(a,resize)
    except Exception as e:
        print(str(e))
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv(r'C:\ICTS\ICTS DATASET\pp1u.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (319, 128)
descriptor shape  1  :  (413, 128)
descriptor shape  2  :  (351, 128)
descriptor shape  3  :  (269, 128)
descriptor shape  4  :  (301, 128)
descriptor shape  5  :  (336, 128)
descriptor shape  6  :  (342, 128)
descriptor shape  7  :  (279, 128)
descriptor shape  8  :  (302, 128)
descriptor shape  9  :  (301, 128)
descriptor shape  10  :  (305, 128)
descriptor shape  11  :  (314, 128)
descriptor shape  12  :  (370, 128)
descriptor shape  13  :  (345, 128)
descriptor shape  14  :  (325, 128)
descriptor shape  15  :  (362, 128)
descriptor shape  16  :  (199, 128)
descriptor shape  17  :  (349, 128)
descriptor shape  18  :  (384, 128)
descriptor shape  19  :  (369, 128)
descriptor shape  20  :  (323, 128)
descriptor shape  21  :  (320, 128)
descriptor shape  22  :  (275, 128)
descriptor shape  23  :  (366, 128)
descriptor shape  24  :  (340, 128)
descriptor shape  25  :  (325, 128)
descriptor shape  26  :  (342, 128)
descriptor shape  27  :  (361, 128)
de

descriptor shape  229  :  (153, 128)
descriptor shape  230  :  (201, 128)
descriptor shape  231  :  (186, 128)
descriptor shape  232  :  (225, 128)
descriptor shape  233  :  (216, 128)
descriptor shape  234  :  (462, 128)
descriptor shape  235  :  (238, 128)
descriptor shape  236  :  (287, 128)
descriptor shape  237  :  (299, 128)
descriptor shape  238  :  (272, 128)
descriptor shape  239  :  (255, 128)
descriptor shape  240  :  (208, 128)
descriptor shape  241  :  (196, 128)
descriptor shape  242  :  (198, 128)
descriptor shape  243  :  (148, 128)
descriptor shape  244  :  (159, 128)
descriptor shape  245  :  (444, 128)
descriptor shape  246  :  (189, 128)
descriptor shape  247  :  (171, 128)
descriptor shape  248  :  (215, 128)
descriptor shape  249  :  (303, 128)
descriptor shape  250  :  (303, 128)
descriptor shape  251  :  (193, 128)
descriptor shape  252  :  (186, 128)
descriptor shape  253  :  (196, 128)
descriptor shape  254  :  (193, 128)
descriptor shape  255  :  (209, 128)
d

descriptor shape  457  :  (452, 128)
descriptor shape  458  :  (423, 128)
descriptor shape  459  :  (464, 128)
descriptor shape  460  :  (479, 128)
descriptor shape  461  :  (457, 128)
descriptor shape  462  :  (492, 128)
descriptor shape  463  :  (527, 128)
descriptor shape  464  :  (545, 128)
descriptor shape  465  :  (454, 128)
descriptor shape  466  :  (500, 128)
descriptor shape  467  :  (295, 128)
descriptor shape  468  :  (443, 128)
descriptor shape  469  :  (331, 128)
descriptor shape  470  :  (415, 128)
descriptor shape  471  :  (475, 128)
descriptor shape  472  :  (494, 128)
descriptor shape  473  :  (484, 128)
descriptor shape  474  :  (482, 128)
descriptor shape  475  :  (465, 128)
descriptor shape  476  :  (473, 128)
descriptor shape  477  :  (455, 128)
descriptor shape  478  :  (318, 128)
descriptor shape  479  :  (420, 128)
descriptor shape  480  :  (409, 128)
descriptor shape  481  :  (469, 128)
descriptor shape  482  :  (344, 128)
descriptor shape  483  :  (447, 128)
d

descriptor shape  681  :  (246, 128)
descriptor shape  682  :  (227, 128)
descriptor shape  683  :  (252, 128)
descriptor shape  684  :  (207, 128)
descriptor shape  685  :  (174, 128)
descriptor shape  686  :  (179, 128)
descriptor shape  687  :  (181, 128)
descriptor shape  688  :  (382, 128)
descriptor shape  689  :  (330, 128)
descriptor shape  690  :  (199, 128)
descriptor shape  691  :  (279, 128)
descriptor shape  692  :  (276, 128)
descriptor shape  693  :  (175, 128)
descriptor shape  694  :  (196, 128)
descriptor shape  695  :  (191, 128)
descriptor shape  696  :  (177, 128)
descriptor shape  697  :  (232, 128)
descriptor shape  698  :  (197, 128)
descriptor shape  699  :  (148, 128)
descriptor shape  700  :  (346, 128)
descriptor shape  701  :  (292, 128)
descriptor shape  702  :  (187, 128)
descriptor shape  703  :  (190, 128)
descriptor shape  704  :  (174, 128)
descriptor shape  705  :  (143, 128)
descriptor shape  706  :  (136, 128)
descriptor shape  707  :  (184, 128)
d

descriptor shape  909  :  (238, 128)
descriptor shape  910  :  (192, 128)
descriptor shape  911  :  (233, 128)
descriptor shape  912  :  (294, 128)
descriptor shape  913  :  (249, 128)
descriptor shape  914  :  (280, 128)
descriptor shape  915  :  (117, 128)
descriptor shape  916  :  (138, 128)
descriptor shape  917  :  (134, 128)
descriptor shape  918  :  (128, 128)
descriptor shape  919  :  (169, 128)
descriptor shape  920  :  (126, 128)
descriptor shape  921  :  (140, 128)
descriptor shape  922  :  (208, 128)
descriptor shape  923  :  (252, 128)
descriptor shape  924  :  (151, 128)
descriptor shape  925  :  (148, 128)
descriptor shape  926  :  (145, 128)
descriptor shape  927  :  (109, 128)
descriptor shape  928  :  (108, 128)
descriptor shape  929  :  (134, 128)
descriptor shape  930  :  (120, 128)
descriptor shape  931  :  (120, 128)
descriptor shape  932  :  (145, 128)
descriptor shape  933  :  (451, 128)
descriptor shape  934  :  (235, 128)
descriptor shape  935  :  (135, 128)
d

descriptor shape  1130  :  (256, 128)
descriptor shape  1131  :  (194, 128)
descriptor shape  1132  :  (214, 128)
descriptor shape  1133  :  (165, 128)
descriptor shape  1134  :  (254, 128)
descriptor shape  1135  :  (165, 128)
descriptor shape  1136  :  (104, 128)
descriptor shape  1137  :  (156, 128)
descriptor shape  1138  :  (146, 128)
descriptor shape  1139  :  (96, 128)
descriptor shape  1140  :  (109, 128)
descriptor shape  1141  :  (82, 128)
descriptor shape  1142  :  (304, 128)
descriptor shape  1143  :  (125, 128)
descriptor shape  1144  :  (269, 128)
descriptor shape  1145  :  (105, 128)
descriptor shape  1146  :  (109, 128)
descriptor shape  1147  :  (104, 128)
descriptor shape  1148  :  (88, 128)
descriptor shape  1149  :  (209, 128)
descriptor shape  1150  :  (199, 128)
descriptor shape  1151  :  (196, 128)
descriptor shape  1152  :  (206, 128)
descriptor shape  1153  :  (180, 128)
descriptor shape  1154  :  (276, 128)
descriptor shape  1155  :  (171, 128)
descriptor shap

descriptor shape  1353  :  (125, 128)
descriptor shape  1354  :  (112, 128)
descriptor shape  1355  :  (191, 128)
descriptor shape  1356  :  (109, 128)
descriptor shape  1357  :  (104, 128)
descriptor shape  1358  :  (91, 128)
descriptor shape  1359  :  (112, 128)
descriptor shape  1360  :  (111, 128)
descriptor shape  1361  :  (110, 128)
descriptor shape  1362  :  (104, 128)
descriptor shape  1363  :  (113, 128)
descriptor shape  1364  :  (210, 128)
descriptor shape  1365  :  (138, 128)
descriptor shape  1366  :  (215, 128)
descriptor shape  1367  :  (130, 128)
descriptor shape  1368  :  (115, 128)
descriptor shape  1369  :  (140, 128)
descriptor shape  1370  :  (129, 128)
descriptor shape  1371  :  (119, 128)
descriptor shape  1372  :  (139, 128)
descriptor shape  1373  :  (145, 128)
descriptor shape  1374  :  (133, 128)
descriptor shape  1375  :  (140, 128)
descriptor shape  1376  :  (217, 128)
descriptor shape  1377  :  (198, 128)
descriptor shape  1378  :  (111, 128)
descriptor sh

descriptor shape  1570  :  (200, 128)
descriptor shape  1571  :  (254, 128)
descriptor shape  1572  :  (168, 128)
descriptor shape  1573  :  (201, 128)
descriptor shape  1574  :  (194, 128)
descriptor shape  1575  :  (204, 128)
descriptor shape  1576  :  (174, 128)
descriptor shape  1577  :  (221, 128)
descriptor shape  1578  :  (214, 128)
descriptor shape  1579  :  (192, 128)
descriptor shape  1580  :  (184, 128)
descriptor shape  1581  :  (162, 128)
descriptor shape  1582  :  (244, 128)
descriptor shape  1583  :  (223, 128)
descriptor shape  1584  :  (404, 128)
descriptor shape  1585  :  (379, 128)
descriptor shape  1586  :  (366, 128)
descriptor shape  1587  :  (460, 128)
descriptor shape  1588  :  (410, 128)
descriptor shape  1589  :  (405, 128)
descriptor shape  1590  :  (402, 128)
descriptor shape  1591  :  (388, 128)
descriptor shape  1592  :  (252, 128)
descriptor shape  1593  :  (264, 128)
descriptor shape  1594  :  (280, 128)
descriptor shape  1595  :  (307, 128)
descriptor s

descriptor shape  1794  :  (246, 128)
descriptor shape  1795  :  (249, 128)
descriptor shape  1796  :  (217, 128)
descriptor shape  1797  :  (442, 128)
descriptor shape  1798  :  (233, 128)
descriptor shape  1799  :  (230, 128)
descriptor shape  1800  :  (302, 128)
descriptor shape  1801  :  (258, 128)
descriptor shape  1802  :  (149, 128)
descriptor shape  1803  :  (215, 128)
descriptor shape  1804  :  (204, 128)
descriptor shape  1805  :  (232, 128)
descriptor shape  1806  :  (253, 128)
descriptor shape  1807  :  (233, 128)
descriptor shape  1808  :  (376, 128)
descriptor shape  1809  :  (257, 128)
descriptor shape  1810  :  (244, 128)
descriptor shape  1811  :  (284, 128)
descriptor shape  1812  :  (279, 128)
descriptor shape  1813  :  (299, 128)
descriptor shape  1814  :  (315, 128)
descriptor shape  1815  :  (271, 128)
descriptor shape  1816  :  (195, 128)
descriptor shape  1817  :  (278, 128)
descriptor shape  1818  :  (256, 128)
descriptor shape  1819  :  (431, 128)
descriptor s

descriptor shape  2016  :  (191, 128)
descriptor shape  2017  :  (191, 128)
descriptor shape  2018  :  (204, 128)
descriptor shape  2019  :  (194, 128)
descriptor shape  2020  :  (172, 128)
descriptor shape  2021  :  (242, 128)
descriptor shape  2022  :  (175, 128)
descriptor shape  2023  :  (178, 128)
descriptor shape  2024  :  (192, 128)
descriptor shape  2025  :  (190, 128)
descriptor shape  2026  :  (198, 128)
descriptor shape  2027  :  (175, 128)
descriptor shape  2028  :  (178, 128)
descriptor shape  2029  :  (147, 128)
descriptor shape  2030  :  (175, 128)
descriptor shape  2031  :  (353, 128)
descriptor shape  2032  :  (206, 128)
descriptor shape  2033  :  (320, 128)
descriptor shape  2034  :  (448, 128)
descriptor shape  2035  :  (243, 128)
descriptor shape  2036  :  (361, 128)
descriptor shape  2037  :  (303, 128)
descriptor shape  2038  :  (393, 128)
descriptor shape  2039  :  (425, 128)
descriptor shape  2040  :  (363, 128)
descriptor shape  2041  :  (349, 128)
descriptor s

descriptor shape  2241  :  (283, 128)
descriptor shape  2242  :  (194, 128)
descriptor shape  2243  :  (218, 128)
descriptor shape  2244  :  (222, 128)
descriptor shape  2245  :  (279, 128)
descriptor shape  2246  :  (302, 128)
descriptor shape  2247  :  (366, 128)
descriptor shape  2248  :  (360, 128)
descriptor shape  2249  :  (316, 128)
descriptor shape  2250  :  (306, 128)
descriptor shape  2251  :  (268, 128)
descriptor shape  2252  :  (244, 128)
descriptor shape  2253  :  (199, 128)
descriptor shape  2254  :  (183, 128)
descriptor shape  2255  :  (149, 128)
descriptor shape  2256  :  (129, 128)
descriptor shape  2257  :  (170, 128)
descriptor shape  2258  :  (187, 128)
descriptor shape  2259  :  (228, 128)
descriptor shape  2260  :  (394, 128)
descriptor shape  2261  :  (368, 128)
descriptor shape  2262  :  (204, 128)
descriptor shape  2263  :  (204, 128)
descriptor shape  2264  :  (250, 128)
descriptor shape  2265  :  (236, 128)
descriptor shape  2266  :  (235, 128)
descriptor s

descriptor shape  2458  :  (378, 128)
descriptor shape  2459  :  (396, 128)
descriptor shape  2460  :  (374, 128)
descriptor shape  2461  :  (392, 128)
descriptor shape  2462  :  (381, 128)
descriptor shape  2463  :  (380, 128)
descriptor shape  2464  :  (373, 128)
descriptor shape  2465  :  (420, 128)
descriptor shape  2466  :  (367, 128)
descriptor shape  2467  :  (366, 128)
descriptor shape  2468  :  (413, 128)
descriptor shape  2469  :  (377, 128)
descriptor shape  2470  :  (364, 128)
descriptor shape  2471  :  (413, 128)
descriptor shape  2472  :  (223, 128)
descriptor shape  2473  :  (252, 128)
descriptor shape  2474  :  (246, 128)
descriptor shape  2475  :  (232, 128)
descriptor shape  2476  :  (419, 128)
descriptor shape  2477  :  (235, 128)
descriptor shape  2478  :  (242, 128)
descriptor shape  2479  :  (317, 128)
descriptor shape  2480  :  (319, 128)
descriptor shape  2481  :  (362, 128)
descriptor shape  2482  :  (390, 128)
descriptor shape  2483  :  (405, 128)
descriptor s

descriptor shape  2676  :  (302, 128)
descriptor shape  2677  :  (228, 128)
descriptor shape  2678  :  (381, 128)
descriptor shape  2679  :  (256, 128)
descriptor shape  2680  :  (244, 128)
descriptor shape  2681  :  (243, 128)
descriptor shape  2682  :  (281, 128)
descriptor shape  2683  :  (296, 128)
descriptor shape  2684  :  (213, 128)
descriptor shape  2685  :  (288, 128)
descriptor shape  2686  :  (299, 128)
descriptor shape  2687  :  (295, 128)
descriptor shape  2688  :  (326, 128)
descriptor shape  2689  :  (369, 128)
descriptor shape  2690  :  (197, 128)
descriptor shape  2691  :  (211, 128)
descriptor shape  2692  :  (246, 128)
descriptor shape  2693  :  (255, 128)
descriptor shape  2694  :  (252, 128)
descriptor shape  2695  :  (244, 128)
descriptor shape  2696  :  (247, 128)
descriptor shape  2697  :  (274, 128)
descriptor shape  2698  :  (249, 128)
descriptor shape  2699  :  (240, 128)
descriptor shape  2700  :  (343, 128)
descriptor shape  2701  :  (312, 128)
descriptor s

descriptor shape  2899  :  (168, 128)
descriptor shape  2900  :  (222, 128)
descriptor shape  2901  :  (151, 128)
descriptor shape  2902  :  (218, 128)
descriptor shape  2903  :  (181, 128)
descriptor shape  2904  :  (193, 128)
descriptor shape  2905  :  (185, 128)
descriptor shape  2906  :  (338, 128)
descriptor shape  2907  :  (199, 128)
descriptor shape  2908  :  (187, 128)
descriptor shape  2909  :  (234, 128)
descriptor shape  2910  :  (206, 128)
descriptor shape  2911  :  (213, 128)
descriptor shape  2912  :  (217, 128)
descriptor shape  2913  :  (225, 128)
descriptor shape  2914  :  (241, 128)
descriptor shape  2915  :  (262, 128)
descriptor shape  2916  :  (166, 128)
descriptor shape  2917  :  (162, 128)
descriptor shape  2918  :  (354, 128)
descriptor shape  2919  :  (185, 128)
descriptor shape  2920  :  (173, 128)
descriptor shape  2921  :  (169, 128)
descriptor shape  2922  :  (209, 128)
descriptor shape  2923  :  (136, 128)
descriptor shape  2924  :  (181, 128)
descriptor s

In [347]:
data1 = pd.read_csv(r'C:\ICTS\ICTS DATASET\pp1u.csv',header=None,dtype='uint8')
#MemoryError: Unable to allocate 166. MiB for an array with shape (128, 169606) and data type float64,
#Double-precision floating-point format

data1=data1.astype(np.uint8) 
#as unit8 contain 1 byte(8bit) and ranges from 0 to 255
data1

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0        23   31   14    3    1    2    7    7   24   14  ...    1    4    1   
1         0    0    0    0    0    0    0    0   10   25  ...    2    9   83   
2         0    0    6    6    0    0    0    0    0   13  ...   27   34   48   
3         0    3    1    3   23    8    0    0    1   15  ...   46   14    0   
4         0    0    0    0    0    0    0    0    0   14  ...   24   86   24   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
788612   50   54   12   33   15    0    0    0   70   49  ...    3   19    0   
788613   14    1    9   34    7    0    0    8  100    1  ...    0    0    5   
788614    9  154  125    0    0    0    0    1   89  154  ...    0    0    0   
788615   43   83   23    0    0    0    0    0  153  141  ...    3    2    0   
788616    0    0    0    0    0    0    0    0   14    1  ...    3   19    5   

        121  122  123  124  125  126  127  
0         0    0    0    0    0    0    0  
1         3    0    0    2   34   25   15  
2        44    2    0    1    5    8    7  
3         0    0    0    0    0    0    0  
4         6    0    0    0    2    1    3  
...     ...  ...  ...  ...  ...  ...  ...  
788612   23    6    3  129   85    0    0  
788613   36   53    0    0    0    0    0  
788614    2    0    0    0    0    0    0  
788615    4   23   12    1    0    0    0  
788616    1   91   76    0    0    3  126  

[788617 rows x 128 columns]

# Negative Images

In [348]:
i=0
for filename in os.listdir(folder2):
    try:
        path=os.path.join(folder2,filename)
        a=cv2.imread(path)

        #resize image
        resize=(180,230)
        img=cv2.resize(a,resize)
    except Exception as e:
        print(str(e))
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv(r'C:\ICTS\ICTS DATASET\pn1u.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (109, 128)
descriptor shape  1  :  (123, 128)
descriptor shape  2  :  (120, 128)
descriptor shape  3  :  (118, 128)
descriptor shape  4  :  (194, 128)
descriptor shape  5  :  (202, 128)
descriptor shape  6  :  (189, 128)
descriptor shape  7  :  (182, 128)
descriptor shape  8  :  (139, 128)
descriptor shape  9  :  (94, 128)
descriptor shape  10  :  (93, 128)
descriptor shape  11  :  (81, 128)
descriptor shape  12  :  (85, 128)
descriptor shape  13  :  (185, 128)
descriptor shape  14  :  (115, 128)
descriptor shape  15  :  (108, 128)
descriptor shape  16  :  (112, 128)
descriptor shape  17  :  (100, 128)
descriptor shape  18  :  (107, 128)
descriptor shape  19  :  (140, 128)
descriptor shape  20  :  (142, 128)
descriptor shape  21  :  (112, 128)
descriptor shape  22  :  (88, 128)
descriptor shape  23  :  (122, 128)
descriptor shape  24  :  (223, 128)
descriptor shape  25  :  (98, 128)
descriptor shape  26  :  (131, 128)
descriptor shape  27  :  (110, 128)
descript

descriptor shape  233  :  (198, 128)
descriptor shape  234  :  (169, 128)
descriptor shape  235  :  (135, 128)
descriptor shape  236  :  (310, 128)
descriptor shape  237  :  (265, 128)
descriptor shape  238  :  (249, 128)
descriptor shape  239  :  (303, 128)
descriptor shape  240  :  (182, 128)
descriptor shape  241  :  (126, 128)
descriptor shape  242  :  (277, 128)
descriptor shape  243  :  (196, 128)
descriptor shape  244  :  (171, 128)
descriptor shape  245  :  (200, 128)
descriptor shape  246  :  (129, 128)
descriptor shape  247  :  (203, 128)
descriptor shape  248  :  (136, 128)
descriptor shape  249  :  (83, 128)
descriptor shape  250  :  (450, 128)
descriptor shape  251  :  (506, 128)
descriptor shape  252  :  (447, 128)
descriptor shape  253  :  (256, 128)
descriptor shape  254  :  (358, 128)
descriptor shape  255  :  (105, 128)
descriptor shape  256  :  (62, 128)
descriptor shape  257  :  (124, 128)
descriptor shape  258  :  (382, 128)
descriptor shape  259  :  (328, 128)
des

descriptor shape  458  :  (91, 128)
descriptor shape  459  :  (343, 128)
descriptor shape  460  :  (359, 128)
descriptor shape  461  :  (376, 128)
descriptor shape  462  :  (283, 128)
descriptor shape  463  :  (279, 128)
descriptor shape  464  :  (136, 128)
descriptor shape  465  :  (205, 128)
descriptor shape  466  :  (312, 128)
descriptor shape  467  :  (365, 128)
descriptor shape  468  :  (151, 128)
descriptor shape  469  :  (177, 128)
descriptor shape  470  :  (174, 128)
descriptor shape  471  :  (255, 128)
descriptor shape  472  :  (196, 128)
descriptor shape  473  :  (285, 128)
descriptor shape  474  :  (508, 128)
descriptor shape  475  :  (133, 128)
descriptor shape  476  :  (192, 128)
descriptor shape  477  :  (205, 128)
descriptor shape  478  :  (199, 128)
descriptor shape  479  :  (221, 128)
descriptor shape  480  :  (162, 128)
descriptor shape  481  :  (390, 128)
descriptor shape  482  :  (239, 128)
descriptor shape  483  :  (110, 128)
descriptor shape  484  :  (273, 128)
de

descriptor shape  682  :  (416, 128)
descriptor shape  683  :  (403, 128)
descriptor shape  684  :  (316, 128)
descriptor shape  685  :  (342, 128)
descriptor shape  686  :  (370, 128)
descriptor shape  687  :  (464, 128)
descriptor shape  688  :  (340, 128)
descriptor shape  689  :  (412, 128)
descriptor shape  690  :  (241, 128)
descriptor shape  691  :  (215, 128)
descriptor shape  692  :  (200, 128)
descriptor shape  693  :  (305, 128)
descriptor shape  694  :  (168, 128)
descriptor shape  695  :  (206, 128)
descriptor shape  696  :  (72, 128)
descriptor shape  697  :  (171, 128)
descriptor shape  698  :  (458, 128)
descriptor shape  699  :  (258, 128)
descriptor shape  700  :  (395, 128)
descriptor shape  701  :  (231, 128)
descriptor shape  702  :  (340, 128)
descriptor shape  703  :  (428, 128)
descriptor shape  704  :  (319, 128)
descriptor shape  705  :  (321, 128)
descriptor shape  706  :  (452, 128)
descriptor shape  707  :  (114, 128)
descriptor shape  708  :  (122, 128)
de

descriptor shape  906  :  (19, 128)
descriptor shape  907  :  (324, 128)
descriptor shape  908  :  (249, 128)
descriptor shape  909  :  (264, 128)
descriptor shape  910  :  (234, 128)
descriptor shape  911  :  (209, 128)
descriptor shape  912  :  (196, 128)
descriptor shape  913  :  (230, 128)
descriptor shape  914  :  (248, 128)
descriptor shape  915  :  (240, 128)
descriptor shape  916  :  (253, 128)
descriptor shape  917  :  (242, 128)
descriptor shape  918  :  (216, 128)
descriptor shape  919  :  (268, 128)
descriptor shape  920  :  (262, 128)
descriptor shape  921  :  (180, 128)
descriptor shape  922  :  (274, 128)
descriptor shape  923  :  (189, 128)
descriptor shape  924  :  (226, 128)
descriptor shape  925  :  (244, 128)
descriptor shape  926  :  (226, 128)
descriptor shape  927  :  (244, 128)
descriptor shape  928  :  (342, 128)
descriptor shape  929  :  (335, 128)
descriptor shape  930  :  (272, 128)
descriptor shape  931  :  (231, 128)
descriptor shape  932  :  (229, 128)
de

descriptor shape  1127  :  (117, 128)
descriptor shape  1128  :  (124, 128)
descriptor shape  1129  :  (131, 128)
descriptor shape  1130  :  (133, 128)
descriptor shape  1131  :  (141, 128)
descriptor shape  1132  :  (148, 128)
descriptor shape  1133  :  (143, 128)
descriptor shape  1134  :  (141, 128)
descriptor shape  1135  :  (185, 128)
descriptor shape  1136  :  (142, 128)
descriptor shape  1137  :  (143, 128)
descriptor shape  1138  :  (125, 128)
descriptor shape  1139  :  (130, 128)
descriptor shape  1140  :  (120, 128)
descriptor shape  1141  :  (128, 128)
descriptor shape  1142  :  (126, 128)
descriptor shape  1143  :  (126, 128)
descriptor shape  1144  :  (125, 128)
descriptor shape  1145  :  (138, 128)
descriptor shape  1146  :  (79, 128)
descriptor shape  1147  :  (126, 128)
descriptor shape  1148  :  (138, 128)
descriptor shape  1149  :  (126, 128)
descriptor shape  1150  :  (135, 128)
descriptor shape  1151  :  (121, 128)
descriptor shape  1152  :  (133, 128)
descriptor sh

descriptor shape  1343  :  (266, 128)
descriptor shape  1344  :  (322, 128)
descriptor shape  1345  :  (333, 128)
descriptor shape  1346  :  (162, 128)
descriptor shape  1347  :  (260, 128)
descriptor shape  1348  :  (262, 128)
descriptor shape  1349  :  (352, 128)
descriptor shape  1350  :  (286, 128)
descriptor shape  1351  :  (425, 128)
descriptor shape  1352  :  (193, 128)
descriptor shape  1353  :  (303, 128)
descriptor shape  1354  :  (462, 128)
descriptor shape  1355  :  (201, 128)
descriptor shape  1356  :  (415, 128)
descriptor shape  1357  :  (131, 128)
descriptor shape  1358  :  (316, 128)
descriptor shape  1359  :  (377, 128)
descriptor shape  1360  :  (356, 128)
descriptor shape  1361  :  (282, 128)
descriptor shape  1362  :  (151, 128)
descriptor shape  1363  :  (236, 128)
descriptor shape  1364  :  (191, 128)
descriptor shape  1365  :  (120, 128)
descriptor shape  1366  :  (215, 128)
descriptor shape  1367  :  (198, 128)
descriptor shape  1368  :  (136, 128)
descriptor s

descriptor shape  1563  :  (244, 128)
descriptor shape  1564  :  (299, 128)
descriptor shape  1565  :  (332, 128)
descriptor shape  1566  :  (501, 128)
descriptor shape  1567  :  (357, 128)
descriptor shape  1568  :  (150, 128)
descriptor shape  1569  :  (265, 128)
descriptor shape  1570  :  (322, 128)
descriptor shape  1571  :  (385, 128)
descriptor shape  1572  :  (389, 128)
descriptor shape  1573  :  (247, 128)
descriptor shape  1574  :  (355, 128)
descriptor shape  1575  :  (328, 128)
descriptor shape  1576  :  (190, 128)
descriptor shape  1577  :  (254, 128)
descriptor shape  1578  :  (300, 128)
descriptor shape  1579  :  (183, 128)
descriptor shape  1580  :  (100, 128)
descriptor shape  1581  :  (170, 128)
descriptor shape  1582  :  (386, 128)
descriptor shape  1583  :  (274, 128)
descriptor shape  1584  :  (84, 128)
descriptor shape  1585  :  (298, 128)
descriptor shape  1586  :  (514, 128)
descriptor shape  1587  :  (513, 128)
descriptor shape  1588  :  (333, 128)
descriptor sh

descriptor shape  1782  :  (54, 128)
descriptor shape  1783  :  (169, 128)
descriptor shape  1784  :  (193, 128)
descriptor shape  1785  :  (176, 128)
descriptor shape  1786  :  (138, 128)
descriptor shape  1787  :  (448, 128)
descriptor shape  1788  :  (173, 128)
descriptor shape  1789  :  (200, 128)
descriptor shape  1790  :  (173, 128)
descriptor shape  1791  :  (164, 128)
descriptor shape  1792  :  (221, 128)
descriptor shape  1793  :  (110, 128)
descriptor shape  1794  :  (302, 128)
descriptor shape  1795  :  (212, 128)
descriptor shape  1796  :  (294, 128)
descriptor shape  1797  :  (253, 128)
descriptor shape  1798  :  (216, 128)
descriptor shape  1799  :  (360, 128)
descriptor shape  1800  :  (373, 128)
descriptor shape  1801  :  (186, 128)
descriptor shape  1802  :  (160, 128)
descriptor shape  1803  :  (16, 128)
descriptor shape  1804  :  (317, 128)
descriptor shape  1805  :  (184, 128)
descriptor shape  1806  :  (111, 128)
descriptor shape  1807  :  (147, 128)
descriptor sha

descriptor shape  2004  :  (241, 128)
descriptor shape  2005  :  (201, 128)
descriptor shape  2006  :  (133, 128)
descriptor shape  2007  :  (145, 128)
descriptor shape  2008  :  (112, 128)
descriptor shape  2009  :  (115, 128)
descriptor shape  2010  :  (146, 128)
descriptor shape  2011  :  (146, 128)
descriptor shape  2012  :  (175, 128)
descriptor shape  2013  :  (111, 128)
descriptor shape  2014  :  (98, 128)
descriptor shape  2015  :  (80, 128)
descriptor shape  2016  :  (87, 128)
descriptor shape  2017  :  (94, 128)
descriptor shape  2018  :  (84, 128)
descriptor shape  2019  :  (91, 128)
descriptor shape  2020  :  (118, 128)
descriptor shape  2021  :  (107, 128)
descriptor shape  2022  :  (138, 128)
descriptor shape  2023  :  (199, 128)
descriptor shape  2024  :  (120, 128)
descriptor shape  2025  :  (136, 128)
descriptor shape  2026  :  (137, 128)
descriptor shape  2027  :  (139, 128)
descriptor shape  2028  :  (226, 128)
descriptor shape  2029  :  (202, 128)
descriptor shape  

descriptor shape  2222  :  (290, 128)
descriptor shape  2223  :  (290, 128)
descriptor shape  2224  :  (264, 128)
descriptor shape  2225  :  (269, 128)
descriptor shape  2226  :  (258, 128)
descriptor shape  2227  :  (439, 128)
descriptor shape  2228  :  (32, 128)
descriptor shape  2229  :  (645, 128)
descriptor shape  2230  :  (206, 128)
descriptor shape  2231  :  (178, 128)
descriptor shape  2232  :  (263, 128)
descriptor shape  2233  :  (333, 128)
descriptor shape  2234  :  (357, 128)
descriptor shape  2235  :  (221, 128)
descriptor shape  2236  :  (323, 128)
descriptor shape  2237  :  (252, 128)
descriptor shape  2238  :  (129, 128)
descriptor shape  2239  :  (269, 128)
descriptor shape  2240  :  (177, 128)
descriptor shape  2241  :  (231, 128)
descriptor shape  2242  :  (192, 128)
descriptor shape  2243  :  (220, 128)
descriptor shape  2244  :  (175, 128)
descriptor shape  2245  :  (160, 128)
descriptor shape  2246  :  (141, 128)
descriptor shape  2247  :  (523, 128)
descriptor sh

descriptor shape  2438  :  (368, 128)
descriptor shape  2439  :  (332, 128)
descriptor shape  2440  :  (612, 128)
descriptor shape  2441  :  (388, 128)
descriptor shape  2442  :  (152, 128)
descriptor shape  2443  :  (177, 128)
descriptor shape  2444  :  (310, 128)
descriptor shape  2445  :  (476, 128)
descriptor shape  2446  :  (411, 128)
descriptor shape  2447  :  (205, 128)
descriptor shape  2448  :  (43, 128)
descriptor shape  2449  :  (69, 128)
descriptor shape  2450  :  (256, 128)
descriptor shape  2451  :  (85, 128)
descriptor shape  2452  :  (569, 128)
descriptor shape  2453  :  (351, 128)
descriptor shape  2454  :  (178, 128)
descriptor shape  2455  :  (52, 128)
descriptor shape  2456  :  (420, 128)
descriptor shape  2457  :  (330, 128)
descriptor shape  2458  :  (386, 128)
descriptor shape  2459  :  (297, 128)
descriptor shape  2460  :  (270, 128)
descriptor shape  2461  :  (127, 128)
descriptor shape  2462  :  (207, 128)
descriptor shape  2463  :  (284, 128)
descriptor shape

descriptor shape  2655  :  (325, 128)
descriptor shape  2656  :  (258, 128)
descriptor shape  2657  :  (68, 128)
descriptor shape  2658  :  (412, 128)
descriptor shape  2659  :  (162, 128)
descriptor shape  2660  :  (247, 128)
descriptor shape  2661  :  (115, 128)
descriptor shape  2662  :  (311, 128)
descriptor shape  2663  :  (381, 128)
descriptor shape  2664  :  (471, 128)
descriptor shape  2665  :  (346, 128)
descriptor shape  2666  :  (91, 128)
descriptor shape  2667  :  (177, 128)
descriptor shape  2668  :  (239, 128)
descriptor shape  2669  :  (609, 128)
descriptor shape  2670  :  (133, 128)
descriptor shape  2671  :  (174, 128)
descriptor shape  2672  :  (199, 128)
descriptor shape  2673  :  (176, 128)
descriptor shape  2674  :  (152, 128)
descriptor shape  2675  :  (230, 128)
descriptor shape  2676  :  (257, 128)
descriptor shape  2677  :  (75, 128)
descriptor shape  2678  :  (297, 128)
descriptor shape  2679  :  (346, 128)
descriptor shape  2680  :  (455, 128)
descriptor shap

descriptor shape  2878  :  (111, 128)
descriptor shape  2879  :  (566, 128)
descriptor shape  2880  :  (189, 128)
descriptor shape  2881  :  (59, 128)
descriptor shape  2882  :  (557, 128)
descriptor shape  2883  :  (281, 128)
descriptor shape  2884  :  (515, 128)
descriptor shape  2885  :  (540, 128)
descriptor shape  2886  :  (199, 128)
descriptor shape  2887  :  (186, 128)
descriptor shape  2888  :  (367, 128)
descriptor shape  2889  :  (315, 128)
descriptor shape  2890  :  (104, 128)
descriptor shape  2891  :  (137, 128)
descriptor shape  2892  :  (117, 128)
descriptor shape  2893  :  (172, 128)
descriptor shape  2894  :  (204, 128)
descriptor shape  2895  :  (264, 128)
descriptor shape  2896  :  (138, 128)
descriptor shape  2897  :  (253, 128)
descriptor shape  2898  :  (278, 128)
descriptor shape  2899  :  (273, 128)
descriptor shape  2900  :  (273, 128)
descriptor shape  2901  :  (152, 128)
descriptor shape  2902  :  (113, 128)
descriptor shape  2903  :  (224, 128)
descriptor sh

In [349]:
data2= pd.read_csv(r'C:\ICTS\ICTS DATASET\pn1u.csv',header=None,dtype='uint8')
data2=data2.astype(np.uint8)
data2

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0        45   26    8    1    0    0    0    2  182   33  ...    0    2    0   
1        23    0    0    1    4    2    0   11  153    0  ...    1    8    2   
2        71    5    0    0    0    1    1    7  153   21  ...    0    0    1   
3        25   33   26   47   15    0    0    0  148  110  ...    0   40  107   
4       135   77    7    4    0    1    4   11   83   61  ...    0   34   31   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
692114    7    0    0    0    7    7    3    8  110    9  ...    0    0  112   
692115   24    3    0    0    1    0    0    6  125   60  ...   23   12   26   
692116   41    2    0    0    0    0    0    1  214   12  ...    7   32    6   
692117   79   68    0    0    0    0    0    0  154   56  ...    0    0    0   
692118   28    5    0    0    6   13   34   75   58   32  ...   23  134   14   

        121  122  123  124  125  126  127  
0         0    0    0    0    0    0    0  
1         4    2    9   20    0    0    0  
2         2    0    4   84    3    0    0  
3         0    0    1   11    2    1   35  
4         0    0    5    7    0    0   20  
...     ...  ...  ...  ...  ...  ...  ...  
692114   20    5   12   64    6    1   10  
692115   33    3    2    3   30   22    4  
692116    1    0    2    5    0    5   13  
692117    0    2   24   21    0    0    0  
692118    0    0   41   38    1    6  117  

[692119 rows x 128 columns]

# Appending all data

In [418]:
data=data1.append(data2)

In [419]:
csv_data=data.to_csv(r'C:\ICTS\ICTS DATASET\Sift_Finalp1u.csv', mode='a', header=False,index=False)

In [420]:
data

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0        23   31   14    3    1    2    7    7   24   14  ...    1    4    1   
1         0    0    0    0    0    0    0    0   10   25  ...    2    9   83   
2         0    0    6    6    0    0    0    0    0   13  ...   27   34   48   
3         0    3    1    3   23    8    0    0    1   15  ...   46   14    0   
4         0    0    0    0    0    0    0    0    0   14  ...   24   86   24   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
692114    7    0    0    0    7    7    3    8  110    9  ...    0    0  112   
692115   24    3    0    0    1    0    0    6  125   60  ...   23   12   26   
692116   41    2    0    0    0    0    0    1  214   12  ...    7   32    6   
692117   79   68    0    0    0    0    0    0  154   56  ...    0    0    0   
692118   28    5    0    0    6   13   34   75   58   32  ...   23  134   14   

        121  122  123  124  125  126  127  
0         0    0    0    0    0    0    0  
1         3    0    0    2   34   25   15  
2        44    2    0    1    5    8    7  
3         0    0    0    0    0    0    0  
4         6    0    0    0    2    1    3  
...     ...  ...  ...  ...  ...  ...  ...  
692114   20    5   12   64    6    1   10  
692115   33    3    2    3   30   22    4  
692116    1    0    2    5    0    5   13  
692117    0    2   24   21    0    0    0  
692118    0    0   41   38    1    6  117  

[1480736 rows x 128 columns]

# K means clustering

In [421]:
kmeans = KMeans(n_clusters=15)
kmeans.fit(data)
import pickle
# save the model to disk
filename = 'Kmeans_CL_5_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [422]:
hist=np.histogram(kmeans.labels_,bins=[0,1,2,3,4,5,6,7,8,9])


print('histogram of trained kmeans')
print(hist,"\n")

histogram of trained kmeans
(array([114470,  95017, 112371, 103639, 108896,  93716,  84391, 135096,
       183096], dtype=int64), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])) 



# K means prediction for  Pedestrian class

In [423]:
#performing kmeans prediction of the entire Staircase dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder1):
    try:
        #path
        path=os.path.join(folder1,filename)
        a=cv2.imread(path)

        #resize image
        resize=(280,430)
        img=cv2.resize(a,resize)
    except Exception as e:
        print(str(e))
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans.predict(array_double)
    
    hist=np.histogram(a,bins=[0,1,2,3,4,5,6,7,8,9])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv(r'C:\ICTS\ICTS DATASET\FinalStrp1u.csv', mode='a',header=False,index=False)

# K means prediction for negative images

In [424]:
#performing kmeans prediction of the entire Non_Staircase dataset with the pretrained kmeans model

#initialising i=1; as its the 2nd class
i=1
data=[]
k=0
for filename in os.listdir(folder2):
    try:
        path=os.path.join(folder2,filename)
        a=cv2.imread(path)
        resize=(280,430)
        img=cv2.resize(a,resize)
    except Exception as e:
        print(str(e))
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    sift = cv2.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float' but got 'double', in order to avoid this dtype=np.double
    try:
        array_double = np.array(out, dtype=np.double)
        a=kmeans.predict(array_double)
    except ValueError as v:
        pass
    hist=np.histogram(a,bins=[0,1,2,3,4,5,6,7,8,9])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv(r'C:\ICTS\ICTS DATASET\FinalNstrp1u.csv', mode='a',header=False,index=False)

# Predicted data ( Pedestrian)

In [425]:
#Displaying the kmeans predicted data
print(" Pedestrian")
dat1= pd.read_csv(r'C:\ICTS\ICTS DATASET\FinalStrp1u.csv',header=None)
print(dat1)

 Pedestrian
        0    1    2   3    4   5   6    7    8  9
0      60   47   66  59   55  65  66   60  101  0
1      91   97  107  47   71  75  42  135  133  0
2     121  126  120  43  106  56  31  163  130  0
3      47   25   49  58   37  61  38   47   91  0
4      34   17   37  74   33  61  55   31  118  0
...   ...  ...  ...  ..  ...  ..  ..  ...  ... ..
2995  102  111   96  37   99  46  31  132  107  0
2996  115  114  124  43   91  48  36  133   97  0
2997  113  127  126  42   96  48  32  163  119  0
2998  118   94  133  49  121  46  28  183  117  0
2999  119  103  149  52  103  51  34  181  155  0

[3000 rows x 10 columns]


# Predicted data (Negative images)

In [426]:
print("Non- Pedestrian")
dat2= pd.read_csv(r'C:\ICTS\ICTS DATASET\FinalNstrp1u.csv',header=None)
print(dat2)

Non- Pedestrian
       0   1   2   3   4   5   6   7   8  9
0     11  22   7  16  21  29  17  14  21  1
1     34  23  31  18  30  35  31  43  55  1
2      3  10   6  29  11  49  43  18  20  1
3      0   6   5  61  17  43  46  11  20  1
4     15  28  22  64  33  37  59  21  67  1
...   ..  ..  ..  ..  ..  ..  ..  ..  .. ..
2995   2   8   7  47   8  10  52   9   9  1
2996  10  13   5  53   7  42  68  12  20  1
2997   6   5   4  48  14  29  60  13  19  1
2998   6   6   5  42   9  24  63  10  18  1
2999   4   5   5  57   4  29  63  11  15  1

[3000 rows x 10 columns]


In [427]:
#appending All classes into 1 csv file

A=dat1.append(dat2)

csv_data=A.to_csv('C:\ICTS\ICTS DATASET\FinalFVp1u.csv', mode='a',header=False,index=False)

In [428]:
A

0    1    2   3    4   5   6    7    8  9
0      60   47   66  59   55  65  66   60  101  0
1      91   97  107  47   71  75  42  135  133  0
2     121  126  120  43  106  56  31  163  130  0
3      47   25   49  58   37  61  38   47   91  0
4      34   17   37  74   33  61  55   31  118  0
...   ...  ...  ...  ..  ...  ..  ..  ...  ... ..
2995    2    8    7  47    8  10  52    9    9  1
2996   10   13    5  53    7  42  68   12   20  1
2997    6    5    4  48   14  29  60   13   19  1
2998    6    6    5  42    9  24  63   10   18  1
2999    4    5    5  57    4  29  63   11   15  1

[6000 rows x 10 columns]

In [429]:
x = A.iloc[:,0:9].values

In [430]:
x

array([[ 60,  47,  66, ...,  66,  60, 101],
       [ 91,  97, 107, ...,  42, 135, 133],
       [121, 126, 120, ...,  31, 163, 130],
       ...,
       [  6,   5,   4, ...,  60,  13,  19],
       [  6,   6,   5, ...,  63,  10,  18],
       [  4,   5,   5, ...,  63,  11,  15]], dtype=int64)

In [431]:
y = A.iloc[:,9].values

In [432]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

# Using StandardScaler

In [433]:
from sklearn.preprocessing import StandardScaler
DhoniS = StandardScaler()
Dhoni = DhoniS.fit_transform(x)

In [434]:
Dhoni

array([[ 0.2405264 ,  0.21888303,  0.42002098, ...,  1.47928133,
        -0.12252648,  0.28363039],
       [ 1.1027279 ,  1.95283891,  1.5633905 , ...,  0.17211079,
         1.44235161,  0.9300047 ],
       [ 1.93711644,  2.95853332,  1.9259223 , ..., -0.42700904,
         2.02657277,  0.86940711],
       ...,
       [-1.26137298, -1.23763991, -1.30897683, ...,  1.15248869,
        -1.10318341, -1.37270378],
       [-1.26137298, -1.20296079, -1.28108977, ...,  1.31588501,
        -1.16577854, -1.39290297],
       [-1.31699888, -1.23763991, -1.28108977, ...,  1.31588501,
        -1.1449135 , -1.45350057]])

# Principal Component Analysis

In [435]:
from sklearn.decomposition import PCA

In [436]:
pca = PCA(n_components=None)
pca.fit(Dhoni)

PCA()

In [437]:
Bhumi = pca.transform(Dhoni)

In [438]:
Bhumi

array([[ 7.83578024e-01,  1.42979814e+00,  5.65472718e-02, ...,
         9.49653984e-02, -4.05979974e-01, -1.29084549e-01],
       [ 3.34023145e+00, -2.05226298e-01, -2.39341861e-01, ...,
         4.92733365e-01,  2.13757173e-01, -3.05063021e-01],
       [ 4.74917321e+00, -1.32692815e+00,  3.32041424e-01, ...,
         4.42497793e-02, -8.02645143e-02,  3.16219350e-02],
       ...,
       [-3.07652849e+00,  1.00603100e+00,  2.79920795e-01, ...,
        -1.00159184e-01,  6.01894698e-02,  2.41881504e-02],
       [-3.21816654e+00,  9.00274750e-01,  3.08442594e-01, ...,
         1.38015665e-01,  3.12676961e-02,  3.40893739e-03],
       [-3.25487117e+00,  1.37503989e+00,  4.54313921e-01, ...,
         1.25135084e-01,  1.67335392e-01, -2.39932075e-02]])

In [439]:
Bhumi = pd.DataFrame(Bhumi)

In [440]:
Bhumi

0         1         2         3         4         5         6  \
0     0.783578  1.429798  0.056547 -0.369758 -0.150793 -0.523731  0.094965   
1     3.340231 -0.205226 -0.239342 -0.648065 -0.138679  0.159932  0.492733   
2     4.749173 -1.326928  0.332041 -1.282378  0.463738  0.443398  0.044250   
3    -0.418075  0.589643 -0.106294  0.541748 -0.324001  0.335197  0.005982   
4    -0.705829  1.898710  0.071612  0.747732  0.080733  0.122104  0.191579   
...        ...       ...       ...       ...       ...       ...       ...   
5995 -3.443963  0.470860  0.694227 -0.641236 -0.084287 -0.410677  0.121764   
5996 -2.876066  1.545467  0.035328 -0.767219 -0.504822 -0.663206  0.181873   
5997 -3.076528  1.006031  0.279921 -0.535508 -0.226735 -0.676614 -0.100159   
5998 -3.218167  0.900275  0.308443 -0.641325 -0.235692 -0.941168  0.138016   
5999 -3.254871  1.375040  0.454314 -0.596601 -0.427328 -0.478362  0.125135   

             7         8  
0    -0.405980 -0.129085  
1     0.213757 -0.305063  
2    -0.080265  0.031622  
3    -0.112370 -0.045139  
4    -0.078624 -0.059825  
...        ...       ...  
5995  0.066073 -0.103408  
5996  0.093257  0.092092  
5997  0.060189  0.024188  
5998  0.031268  0.003409  
5999  0.167335 -0.023993  

[6000 rows x 9 columns]

In [441]:
Bhumi.shape

(6000, 9)

In [442]:
print(pca.explained_variance_ratio_) 

[0.58244828 0.22755064 0.07419968 0.04373294 0.02815985 0.01840758
 0.01197279 0.01002123 0.003507  ]


In [443]:
pca = PCA(n_components=3)
pca.fit(Dhoni)

PCA(n_components=3)

In [444]:
# save the model to disk
filename = 'PCA_3_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [445]:
Bhumi = pca.transform(Dhoni)

In [446]:
Bhumi

array([[ 0.78357802,  1.42979814,  0.05654727],
       [ 3.34023145, -0.2052263 , -0.23934186],
       [ 4.74917321, -1.32692815,  0.33204142],
       ...,
       [-3.07652849,  1.006031  ,  0.2799208 ],
       [-3.21816654,  0.90027475,  0.30844259],
       [-3.25487117,  1.37503989,  0.45431392]])

In [447]:
Bhumi.shape

(6000, 3)

In [448]:
print(pca.explained_variance_ratio_) 

[0.58244828 0.22755064 0.07419968]


In [449]:
Bhumi = pd.DataFrame(Bhumi)

In [450]:
Bhumi

0         1         2
0     0.783578  1.429798  0.056547
1     3.340231 -0.205226 -0.239342
2     4.749173 -1.326928  0.332041
3    -0.418075  0.589643 -0.106294
4    -0.705829  1.898710  0.071612
...        ...       ...       ...
5995 -3.443963  0.470860  0.694227
5996 -2.876066  1.545467  0.035328
5997 -3.076528  1.006031  0.279921
5998 -3.218167  0.900275  0.308443
5999 -3.254871  1.375040  0.454314

[6000 rows x 3 columns]

In [451]:
B=pd.concat([Bhumi, pd.DataFrame(y)],axis=1)

In [452]:
B

0         1         2  0
0     0.783578  1.429798  0.056547  0
1     3.340231 -0.205226 -0.239342  0
2     4.749173 -1.326928  0.332041  0
3    -0.418075  0.589643 -0.106294  0
4    -0.705829  1.898710  0.071612  0
...        ...       ...       ... ..
5995 -3.443963  0.470860  0.694227  1
5996 -2.876066  1.545467  0.035328  1
5997 -3.076528  1.006031  0.279921  1
5998 -3.218167  0.900275  0.308443  1
5999 -3.254871  1.375040  0.454314  1

[6000 rows x 4 columns]

In [453]:
csv_data=B.to_csv('C:\ICTS\ICTS DATASET\FinalPCAFVp1u.csv', mode='a',header=False,index=False)

# Training , Testing and Classification

In [454]:
data= pd.read_csv(r'C:\ICTS\ICTS DATASET\FinalPCAFVp1u.csv',header=None)

data

0         1         2  3
0     0.783578  1.429798  0.056547  0
1     3.340231 -0.205226 -0.239342  0
2     4.749173 -1.326928  0.332041  0
3    -0.418075  0.589643 -0.106294  0
4    -0.705829  1.898710  0.071612  0
...        ...       ...       ... ..
5995 -3.443963  0.470860  0.694227  1
5996 -2.876066  1.545467  0.035328  1
5997 -3.076528  1.006031  0.279921  1
5998 -3.218167  0.900275  0.308443  1
5999 -3.254871  1.375040  0.454314  1

[6000 rows x 4 columns]

In [455]:
#assigning x the columns from 1 to 128 for training
x = data.iloc[:,0:3].values
print("X values")
print(x)

#assigning y with the column "Class" as target variable
y = data.iloc[:,3]
print("Y values")
print(y)

X values
[[ 0.78357802  1.42979814  0.05654727]
 [ 3.34023145 -0.2052263  -0.23934186]
 [ 4.74917321 -1.32692815  0.33204142]
 ...
 [-3.07652849  1.006031    0.2799208 ]
 [-3.21816654  0.90027475  0.30844259]
 [-3.25487117  1.37503989  0.45431392]]
Y values
0       0
1       0
2       0
3       0
4       0
       ..
5995    1
5996    1
5997    1
5998    1
5999    1
Name: 3, Length: 6000, dtype: int64


In [456]:
#Dataset split into train and test with 80% Training and 20% Testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.10, random_state=0)

# Decision Tree

In [457]:
#Decision Tree Classifier
from sklearn.metrics import accuracy_score
#Assign model with Decision Tree classifier
model1 = DecisionTreeClassifier(max_depth=13)
filename = 'model1.sav'
pickle.dump(kmeans, open(filename, 'wb'))
#training the model with the Training Variables 
model1.fit(x_train, y_train)
#predicting the traget variable using testing variables
y_pred1 = model1.predict(x_test)

#Results
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred1))
print("Decision Tree Results")
print("Decision Tree Accuracy: ",accuracy_score(y_test, y_pred1)*100,"%")

print("Decision Tree Results")
#print('\nTraining Accuracy: {:.2f}\n'.format(accuracy_score(y_train, y_pred1)))
print('\nTesting Accuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred1)))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred1, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred1, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred1, average='weighted')))

print('\nClassification Report\n')
print(classification_report(y_test, y_pred1, target_names=['Class 1', 'Class 2']))

[[214  67]
 [ 93 226]]
Decision Tree Results
Decision Tree Accuracy:  73.33333333333333 %
Decision Tree Results

Testing Accuracy: 0.73

Weighted Precision: 0.74
Weighted Recall: 0.73
Weighted F1-score: 0.73

Classification Report

              precision    recall  f1-score   support

     Class 1       0.70      0.76      0.73       281
     Class 2       0.77      0.71      0.74       319

    accuracy                           0.73       600
   macro avg       0.73      0.74      0.73       600
weighted avg       0.74      0.73      0.73       600



In [458]:
#Recognition &Validation
#Assigning path with any any class image
data=[]
path=r"C:\ICTS\ICTS DATASET\Positive images\Pedestrian_2\pedestrian34.jpg"


#Repeated the process of image pre-processing and feature extraction
try:
    a=cv2.imread(path)
    resize=(280,430)

    #resize image
    img=cv2.resize(a,resize)
except Exception as e:
    print("corrupt Img")
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

#initialise sift descriptor
sift = cv2.SIFT_create()
keypoints, descriptors = sift.detectAndCompute(gray, None)

#convert the descriptor array into a dataframe format
out=pd.DataFrame(descriptors)
print("Descriptor Shape:",out.shape)

#initialise Kmeans and create 5 clusters


#train the model for the features i.e. for all elements in the Dataframe
array_double = np.array(out, dtype=np.double)
a=kmeans.predict(array_double)

#get the values of the histogram for one image only for 5 clusters i.e. in 5 bins
#kmeans.labels_ give us the label vlaue of the feature that its clustered into
#hist will give the hostogram for all those vlaues
hist=np.histogram(a,bins=[0,1,2,3,4,5,6,7,8,9])

#append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
data.append(hist[0])

Output = pd.DataFrame(data)
print("Histogram:\n",Output)

Descriptor Shape: (867, 128)
Histogram:
     0   1   2   3   4   5   6   7    8
0  43  37  50  58  54  60  31  59  133


In [459]:
from sklearn.preprocessing import StandardScaler
MuktaS = StandardScaler()
Mukta = MuktaS.fit_transform(Output)

In [460]:
Mukta

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [461]:
Mukta.shape

(1, 9)

In [462]:
MB = pca.transform(Mukta)

In [463]:
MB.shape

(1, 3)

In [464]:
MB

array([[-1.23820899e-16,  3.70686128e-17,  2.84395794e-17]])

In [465]:
#prediction
y_pred1 = model1.predict(MB)

#prints the prediction of the class
print(y_pred1)

[1]


# SVC

In [466]:
from sklearn.svm import SVC
DhoniSVM_LK = SVC(kernel='rbf')
Dhoni_LK = DhoniSVM_LK.fit(x_train, y_train)

In [467]:
filename = 'SVC_RBF_PCA_3.sav'
pickle.dump(Dhoni_LK, open(filename, 'wb'))

In [468]:
Dhoni_LK

SVC()

In [469]:
y_pred_LK = Dhoni_LK.predict(x_test)

In [470]:
y_pred_LK

array([1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,

In [471]:
from sklearn.metrics import confusion_matrix

In [472]:
confusion_matrix(y_test, y_pred_LK)

array([[222,  59],
       [ 70, 249]], dtype=int64)

In [473]:
from sklearn.metrics import accuracy_score

In [474]:
accuracy_score(y_test, y_pred_LK)

0.785

In [475]:
y_pred1 = model1.predict(MB)



In [476]:
#print(y_pred1)
print("SVC Results")
#print('\nTraining Accuracy: {:.2f}\n'.format(accuracy_score(y_train, y_pred_LK)))
print('\nTesting Accuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred_LK)))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred_LK, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred_LK, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred_LK, average='weighted')))

print('\nClassification Report\n')
print(classification_report(y_test, y_pred_LK, target_names=['Class 1', 'Class 2']))

SVC Results

Testing Accuracy: 0.79

Weighted Precision: 0.79
Weighted Recall: 0.79
Weighted F1-score: 0.79

Classification Report

              precision    recall  f1-score   support

     Class 1       0.76      0.79      0.77       281
     Class 2       0.81      0.78      0.79       319

    accuracy                           0.79       600
   macro avg       0.78      0.79      0.78       600
weighted avg       0.79      0.79      0.79       600



# Random Forest 

In [477]:
#Random Forest Classifier
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
import pickle
model_rf = RandomForestClassifier(n_estimators = 500)
filename = 'model_rf.sav'
pickle.dump(kmeans, open(filename, 'wb'))
model_rf1 =model_rf.fit(x_train, y_train)
y_pred_rf = model_rf1.predict(x_test)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred_rf)
print("Random Forest Accuracy: ",accuracy_score(y_test, y_pred_rf)*100,"%")

Random Forest Accuracy:  78.66666666666666 %


In [478]:
#print(y_pred1)
print("Random Forest Results")
#print('\nTraining Accuracy: {:.2f}\n'.format(accuracy_score(y_train, y_pred1)))
print('\nTesting Accuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred_rf)))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred_rf, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred_rf, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred_rf, average='weighted')))

print('\nClassification Report\n')
print(classification_report(y_test, y_pred_rf, target_names=['Class 1', 'Class 2']))

Random Forest Results

Testing Accuracy: 0.79

Weighted Precision: 0.79
Weighted Recall: 0.79
Weighted F1-score: 0.79

Classification Report

              precision    recall  f1-score   support

     Class 1       0.78      0.77      0.77       281
     Class 2       0.80      0.81      0.80       319

    accuracy                           0.79       600
   macro avg       0.79      0.79      0.79       600
weighted avg       0.79      0.79      0.79       600



# SVM

In [479]:
# SVM
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
import pickle
SVM_LK = SVC(kernel='rbf')
LK = SVM_LK.fit(x_train, y_train)
filename = 'SVC_RBF_PCA_3.sav'
pickle.dump(LK, open(filename, 'wb'))
y_pred_LK = LK.predict(x_test)
print(accuracy_score(y_test, y_pred_LK))

0.785


In [480]:
#print(y_pred1)
print("SVM Results")
#print('\nTraining Accuracy: {:.2f}\n'.format(accuracy_score(y_train, y_pred1)))
print('\nTesting Accuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred_LK)))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred_LK, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred_LK, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred_LK, average='weighted')))

print('\nClassification Report\n')
print(classification_report(y_test, y_pred_LK, target_names=['Class 1', 'Class 2']))

SVM Results

Testing Accuracy: 0.79

Weighted Precision: 0.79
Weighted Recall: 0.79
Weighted F1-score: 0.79

Classification Report

              precision    recall  f1-score   support

     Class 1       0.76      0.79      0.77       281
     Class 2       0.81      0.78      0.79       319

    accuracy                           0.79       600
   macro avg       0.78      0.79      0.78       600
weighted avg       0.79      0.79      0.79       600



# KNN

In [481]:
# knn
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
import pickle
model_knn = KNeighborsClassifier(n_neighbors=1)
filename = 'model_knn.sav'
pickle.dump(kmeans, open(filename, 'wb'))
model_knn1 =model_knn.fit(x_train, y_train)
y_pred_knn = model_knn1.predict(x_test)
print("KNN Results")
print("KNN Accuracy: ",accuracy_score(y_test, y_pred_knn)*100,"%")

KNN Results
KNN Accuracy:  73.83333333333333 %


In [482]:
#print(y_pred1)
print("KNN Results")
#print('\nTraining Accuracy: {:.2f}\n'.format(accuracy_score(y_train, y_pred1)))
print('\nTesting Accuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred_knn)))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred_knn, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred_knn, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred_knn, average='weighted')))

print('\nClassification Report\n')
print(classification_report(y_test, y_pred_knn, target_names=['Class 1', 'Class 2']))

KNN Results

Testing Accuracy: 0.74

Weighted Precision: 0.74
Weighted Recall: 0.74
Weighted F1-score: 0.74

Classification Report

              precision    recall  f1-score   support

     Class 1       0.73      0.71      0.72       281
     Class 2       0.75      0.76      0.76       319

    accuracy                           0.74       600
   macro avg       0.74      0.74      0.74       600
weighted avg       0.74      0.74      0.74       600



# Logistic regression

In [483]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report

In [484]:
Classifier_LOG_REG = LogisticRegression()

Model_LOG_REG=Classifier_LOG_REG.fit(x_train, y_train)

filename = 'Model_LOG_REG.sav'
pickle.dump(Model_LOG_REG, open(filename, 'wb'))

predictions = Model_LOG_REG.predict(x_test)
print(f"Test Set Accuracy : {accuracy_score(y_test, predictions) * 100} %\n\n")

Test Set Accuracy : 70.0 %


