# Importing libraries

In [165]:
import numpy as np
import pandas as pd
import os
import csv
import cv2
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score

In [166]:
!pip install opencv-python

# Path of positive and negative images

In [167]:
folder1=r"C:\ICTS\ICTS DATASET\Positive images\RightCurve2"
folder2=r"C:\ICTS\ICTS DATASET\Negative_3000"

# Data Pre-processing

# SIFT descriptor

# Class : RightCurve

In [168]:
i=0
for filename in os.listdir(folder1):
    #path
    try:
        path=os.path.join(folder1,filename)
        a=cv2.imread(path)

        #resize image
        resize=(180,230)
        img=cv2.resize(a,resize)
    except Exception as e:
        print(str(e))
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv(r'C:\ICTS\ICTS DATASET\pp1e.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (205, 128)
descriptor shape  1  :  (214, 128)
descriptor shape  2  :  (451, 128)
descriptor shape  3  :  (208, 128)
descriptor shape  4  :  (171, 128)
descriptor shape  5  :  (185, 128)
descriptor shape  6  :  (182, 128)
descriptor shape  7  :  (185, 128)
descriptor shape  8  :  (199, 128)
descriptor shape  9  :  (204, 128)
descriptor shape  10  :  (206, 128)
descriptor shape  11  :  (185, 128)
descriptor shape  12  :  (435, 128)
descriptor shape  13  :  (212, 128)
descriptor shape  14  :  (197, 128)
descriptor shape  15  :  (236, 128)
descriptor shape  16  :  (202, 128)
descriptor shape  17  :  (202, 128)
descriptor shape  18  :  (216, 128)
descriptor shape  19  :  (216, 128)
descriptor shape  20  :  (225, 128)
descriptor shape  21  :  (225, 128)
descriptor shape  22  :  (219, 128)
descriptor shape  23  :  (470, 128)
descriptor shape  24  :  (219, 128)
descriptor shape  25  :  (220, 128)
descriptor shape  26  :  (220, 128)
descriptor shape  27  :  (193, 128)
de

descriptor shape  225  :  (331, 128)
descriptor shape  226  :  (325, 128)
descriptor shape  227  :  (342, 128)
descriptor shape  228  :  (357, 128)
descriptor shape  229  :  (308, 128)
descriptor shape  230  :  (270, 128)
descriptor shape  231  :  (234, 128)
descriptor shape  232  :  (160, 128)
descriptor shape  233  :  (168, 128)
descriptor shape  234  :  (263, 128)
descriptor shape  235  :  (177, 128)
descriptor shape  236  :  (184, 128)
descriptor shape  237  :  (170, 128)
descriptor shape  238  :  (207, 128)
descriptor shape  239  :  (212, 128)
descriptor shape  240  :  (211, 128)
descriptor shape  241  :  (206, 128)
descriptor shape  242  :  (187, 128)
descriptor shape  243  :  (144, 128)
descriptor shape  244  :  (161, 128)
descriptor shape  245  :  (318, 128)
descriptor shape  246  :  (205, 128)
descriptor shape  247  :  (227, 128)
descriptor shape  248  :  (205, 128)
descriptor shape  249  :  (214, 128)
descriptor shape  250  :  (230, 128)
descriptor shape  251  :  (258, 128)
d

descriptor shape  453  :  (302, 128)
descriptor shape  454  :  (294, 128)
descriptor shape  455  :  (165, 128)
descriptor shape  456  :  (314, 128)
descriptor shape  457  :  (296, 128)
descriptor shape  458  :  (320, 128)
descriptor shape  459  :  (356, 128)
descriptor shape  460  :  (356, 128)
descriptor shape  461  :  (374, 128)
descriptor shape  462  :  (407, 128)
descriptor shape  463  :  (438, 128)
descriptor shape  464  :  (457, 128)
descriptor shape  465  :  (442, 128)
descriptor shape  466  :  (243, 128)
descriptor shape  467  :  (220, 128)
descriptor shape  468  :  (462, 128)
descriptor shape  469  :  (463, 128)
descriptor shape  470  :  (499, 128)
descriptor shape  471  :  (506, 128)
descriptor shape  472  :  (516, 128)
descriptor shape  473  :  (519, 128)
descriptor shape  474  :  (500, 128)
descriptor shape  475  :  (493, 128)
descriptor shape  476  :  (274, 128)
descriptor shape  477  :  (267, 128)
descriptor shape  478  :  (220, 128)
descriptor shape  479  :  (276, 128)
d

descriptor shape  679  :  (148, 128)
descriptor shape  680  :  (174, 128)
descriptor shape  681  :  (158, 128)
descriptor shape  682  :  (141, 128)
descriptor shape  683  :  (148, 128)
descriptor shape  684  :  (134, 128)
descriptor shape  685  :  (147, 128)
descriptor shape  686  :  (44, 128)
descriptor shape  687  :  (30, 128)
descriptor shape  688  :  (282, 128)
descriptor shape  689  :  (276, 128)
descriptor shape  690  :  (27, 128)
descriptor shape  691  :  (265, 128)
descriptor shape  692  :  (295, 128)
descriptor shape  693  :  (267, 128)
descriptor shape  694  :  (265, 128)
descriptor shape  695  :  (246, 128)
descriptor shape  696  :  (255, 128)
descriptor shape  697  :  (252, 128)
descriptor shape  698  :  (240, 128)
descriptor shape  699  :  (239, 128)
descriptor shape  700  :  (215, 128)
descriptor shape  701  :  (206, 128)
descriptor shape  702  :  (188, 128)
descriptor shape  703  :  (486, 128)
descriptor shape  704  :  (300, 128)
descriptor shape  705  :  (351, 128)
desc

descriptor shape  907  :  (184, 128)
descriptor shape  908  :  (166, 128)
descriptor shape  909  :  (168, 128)
descriptor shape  910  :  (160, 128)
descriptor shape  911  :  (181, 128)
descriptor shape  912  :  (223, 128)
descriptor shape  913  :  (227, 128)
descriptor shape  914  :  (220, 128)
descriptor shape  915  :  (212, 128)
descriptor shape  916  :  (226, 128)
descriptor shape  917  :  (212, 128)
descriptor shape  918  :  (215, 128)
descriptor shape  919  :  (199, 128)
descriptor shape  920  :  (234, 128)
descriptor shape  921  :  (203, 128)
descriptor shape  922  :  (192, 128)
descriptor shape  923  :  (212, 128)
descriptor shape  924  :  (202, 128)
descriptor shape  925  :  (464, 128)
descriptor shape  926  :  (202, 128)
descriptor shape  927  :  (244, 128)
descriptor shape  928  :  (224, 128)
descriptor shape  929  :  (211, 128)
descriptor shape  930  :  (236, 128)
descriptor shape  931  :  (277, 128)
descriptor shape  932  :  (278, 128)
descriptor shape  933  :  (239, 128)
d

descriptor shape  1126  :  (204, 128)
descriptor shape  1127  :  (204, 128)
descriptor shape  1128  :  (223, 128)
descriptor shape  1129  :  (223, 128)
descriptor shape  1130  :  (206, 128)
descriptor shape  1131  :  (206, 128)
descriptor shape  1132  :  (221, 128)
descriptor shape  1133  :  (113, 128)
descriptor shape  1134  :  (221, 128)
descriptor shape  1135  :  (212, 128)
descriptor shape  1136  :  (212, 128)
descriptor shape  1137  :  (225, 128)
descriptor shape  1138  :  (225, 128)
descriptor shape  1139  :  (207, 128)
descriptor shape  1140  :  (207, 128)
descriptor shape  1141  :  (247, 128)
descriptor shape  1142  :  (247, 128)
descriptor shape  1143  :  (223, 128)
descriptor shape  1144  :  (105, 128)
descriptor shape  1145  :  (223, 128)
descriptor shape  1146  :  (250, 128)
descriptor shape  1147  :  (250, 128)
descriptor shape  1148  :  (226, 128)
descriptor shape  1149  :  (226, 128)
descriptor shape  1150  :  (217, 128)
descriptor shape  1151  :  (217, 128)
descriptor s

descriptor shape  1347  :  (61, 128)
descriptor shape  1348  :  (58, 128)
descriptor shape  1349  :  (58, 128)
descriptor shape  1350  :  (58, 128)
descriptor shape  1351  :  (82, 128)
descriptor shape  1352  :  (84, 128)
descriptor shape  1353  :  (62, 128)
descriptor shape  1354  :  (92, 128)
descriptor shape  1355  :  (127, 128)
descriptor shape  1356  :  (73, 128)
descriptor shape  1357  :  (72, 128)
descriptor shape  1358  :  (204, 128)
descriptor shape  1359  :  (232, 128)
descriptor shape  1360  :  (247, 128)
descriptor shape  1361  :  (309, 128)
descriptor shape  1362  :  (55, 128)
descriptor shape  1363  :  (35, 128)
descriptor shape  1364  :  (33, 128)
descriptor shape  1365  :  (23, 128)
descriptor shape  1366  :  (149, 128)
descriptor shape  1367  :  (72, 128)
descriptor shape  1368  :  (71, 128)
descriptor shape  1369  :  (69, 128)
descriptor shape  1370  :  (60, 128)
descriptor shape  1371  :  (95, 128)
descriptor shape  1372  :  (89, 128)
descriptor shape  1373  :  (96, 

descriptor shape  1572  :  (145, 128)
descriptor shape  1573  :  (172, 128)
descriptor shape  1574  :  (157, 128)
descriptor shape  1575  :  (129, 128)
descriptor shape  1576  :  (155, 128)
descriptor shape  1577  :  (118, 128)
descriptor shape  1578  :  (129, 128)
descriptor shape  1579  :  (138, 128)
descriptor shape  1580  :  (139, 128)
descriptor shape  1581  :  (126, 128)
descriptor shape  1582  :  (119, 128)
descriptor shape  1583  :  (137, 128)
descriptor shape  1584  :  (135, 128)
descriptor shape  1585  :  (214, 128)
descriptor shape  1586  :  (259, 128)
descriptor shape  1587  :  (227, 128)
descriptor shape  1588  :  (215, 128)
descriptor shape  1589  :  (219, 128)
descriptor shape  1590  :  (230, 128)
descriptor shape  1591  :  (233, 128)
descriptor shape  1592  :  (201, 128)
descriptor shape  1593  :  (239, 128)
descriptor shape  1594  :  (244, 128)
descriptor shape  1595  :  (241, 128)
descriptor shape  1596  :  (251, 128)
descriptor shape  1597  :  (224, 128)
descriptor s

descriptor shape  1790  :  (262, 128)
descriptor shape  1791  :  (262, 128)
descriptor shape  1792  :  (295, 128)
descriptor shape  1793  :  (295, 128)
descriptor shape  1794  :  (294, 128)
descriptor shape  1795  :  (294, 128)
descriptor shape  1796  :  (268, 128)
descriptor shape  1797  :  (268, 128)
descriptor shape  1798  :  (239, 128)
descriptor shape  1799  :  (239, 128)
descriptor shape  1800  :  (252, 128)
descriptor shape  1801  :  (252, 128)
descriptor shape  1802  :  (302, 128)
descriptor shape  1803  :  (302, 128)
descriptor shape  1804  :  (297, 128)
descriptor shape  1805  :  (297, 128)
descriptor shape  1806  :  (273, 128)
descriptor shape  1807  :  (273, 128)
descriptor shape  1808  :  (298, 128)
descriptor shape  1809  :  (298, 128)
descriptor shape  1810  :  (286, 128)
descriptor shape  1811  :  (286, 128)
descriptor shape  1812  :  (287, 128)
descriptor shape  1813  :  (276, 128)
descriptor shape  1814  :  (263, 128)
descriptor shape  1815  :  (297, 128)
descriptor s

descriptor shape  2010  :  (196, 128)
descriptor shape  2011  :  (242, 128)
descriptor shape  2012  :  (185, 128)
descriptor shape  2013  :  (161, 128)
descriptor shape  2014  :  (174, 128)
descriptor shape  2015  :  (173, 128)
descriptor shape  2016  :  (176, 128)
descriptor shape  2017  :  (162, 128)
descriptor shape  2018  :  (173, 128)
descriptor shape  2019  :  (164, 128)
descriptor shape  2020  :  (176, 128)
descriptor shape  2021  :  (140, 128)
descriptor shape  2022  :  (127, 128)
descriptor shape  2023  :  (145, 128)
descriptor shape  2024  :  (168, 128)
descriptor shape  2025  :  (150, 128)
descriptor shape  2026  :  (128, 128)
descriptor shape  2027  :  (114, 128)
descriptor shape  2028  :  (131, 128)
descriptor shape  2029  :  (96, 128)
descriptor shape  2030  :  (93, 128)
descriptor shape  2031  :  (239, 128)
descriptor shape  2032  :  (50, 128)
descriptor shape  2033  :  (241, 128)
descriptor shape  2034  :  (234, 128)
descriptor shape  2035  :  (241, 128)
descriptor shap

descriptor shape  2233  :  (310, 128)
descriptor shape  2234  :  (433, 128)
descriptor shape  2235  :  (404, 128)
descriptor shape  2236  :  (257, 128)
descriptor shape  2237  :  (359, 128)
descriptor shape  2238  :  (396, 128)
descriptor shape  2239  :  (402, 128)
descriptor shape  2240  :  (374, 128)
descriptor shape  2241  :  (364, 128)
descriptor shape  2242  :  (380, 128)
descriptor shape  2243  :  (265, 128)
descriptor shape  2244  :  (246, 128)
descriptor shape  2245  :  (214, 128)
descriptor shape  2246  :  (187, 128)
descriptor shape  2247  :  (196, 128)
descriptor shape  2248  :  (214, 128)
descriptor shape  2249  :  (234, 128)
descriptor shape  2250  :  (222, 128)
descriptor shape  2251  :  (210, 128)
descriptor shape  2252  :  (212, 128)
descriptor shape  2253  :  (223, 128)
descriptor shape  2254  :  (228, 128)
descriptor shape  2255  :  (207, 128)
descriptor shape  2256  :  (199, 128)
descriptor shape  2257  :  (301, 128)
descriptor shape  2258  :  (292, 128)
descriptor s

descriptor shape  2459  :  (178, 128)
descriptor shape  2460  :  (206, 128)
descriptor shape  2461  :  (206, 128)
descriptor shape  2462  :  (247, 128)
descriptor shape  2463  :  (282, 128)
descriptor shape  2464  :  (295, 128)
descriptor shape  2465  :  (322, 128)
descriptor shape  2466  :  (263, 128)
descriptor shape  2467  :  (306, 128)
descriptor shape  2468  :  (314, 128)
descriptor shape  2469  :  (324, 128)
descriptor shape  2470  :  (357, 128)
descriptor shape  2471  :  (341, 128)
descriptor shape  2472  :  (297, 128)
descriptor shape  2473  :  (355, 128)
descriptor shape  2474  :  (344, 128)
descriptor shape  2475  :  (361, 128)
descriptor shape  2476  :  (363, 128)
descriptor shape  2477  :  (371, 128)
descriptor shape  2478  :  (261, 128)
descriptor shape  2479  :  (226, 128)
descriptor shape  2480  :  (212, 128)
descriptor shape  2481  :  (211, 128)
descriptor shape  2482  :  (230, 128)
descriptor shape  2483  :  (229, 128)
descriptor shape  2484  :  (209, 128)
descriptor s

descriptor shape  2675  :  (199, 128)
descriptor shape  2676  :  (199, 128)
descriptor shape  2677  :  (194, 128)
descriptor shape  2678  :  (259, 128)
descriptor shape  2679  :  (194, 128)
descriptor shape  2680  :  (188, 128)
descriptor shape  2681  :  (188, 128)
descriptor shape  2682  :  (207, 128)
descriptor shape  2683  :  (207, 128)
descriptor shape  2684  :  (194, 128)
descriptor shape  2685  :  (194, 128)
descriptor shape  2686  :  (180, 128)
descriptor shape  2687  :  (180, 128)
descriptor shape  2688  :  (198, 128)
descriptor shape  2689  :  (259, 128)
descriptor shape  2690  :  (198, 128)
descriptor shape  2691  :  (204, 128)
descriptor shape  2692  :  (204, 128)
descriptor shape  2693  :  (179, 128)
descriptor shape  2694  :  (179, 128)
descriptor shape  2695  :  (203, 128)
descriptor shape  2696  :  (203, 128)
descriptor shape  2697  :  (197, 128)
descriptor shape  2698  :  (197, 128)
descriptor shape  2699  :  (240, 128)
descriptor shape  2700  :  (266, 128)
descriptor s

descriptor shape  2898  :  (219, 128)
descriptor shape  2899  :  (247, 128)
descriptor shape  2900  :  (266, 128)
descriptor shape  2901  :  (233, 128)
descriptor shape  2902  :  (267, 128)
descriptor shape  2903  :  (153, 128)
descriptor shape  2904  :  (173, 128)
descriptor shape  2905  :  (135, 128)
descriptor shape  2906  :  (144, 128)
descriptor shape  2907  :  (145, 128)
descriptor shape  2908  :  (145, 128)
descriptor shape  2909  :  (175, 128)
descriptor shape  2910  :  (151, 128)
descriptor shape  2911  :  (266, 128)
descriptor shape  2912  :  (194, 128)
descriptor shape  2913  :  (210, 128)
descriptor shape  2914  :  (124, 128)
descriptor shape  2915  :  (128, 128)
descriptor shape  2916  :  (149, 128)
descriptor shape  2917  :  (172, 128)
descriptor shape  2918  :  (130, 128)
descriptor shape  2919  :  (145, 128)
descriptor shape  2920  :  (138, 128)
descriptor shape  2921  :  (139, 128)
descriptor shape  2922  :  (293, 128)
descriptor shape  2923  :  (126, 128)
descriptor s

In [169]:
data1 = pd.read_csv(r'C:\ICTS\ICTS DATASET\pp1e.csv',header=None,dtype='uint8')
#MemoryError: Unable to allocate 166. MiB for an array with shape (128, 169606) and data type float64,
#Double-precision floating-point format

data1=data1.astype(np.uint8) 
#as unit8 contain 1 byte(8bit) and ranges from 0 to 255
data1

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0        12    0    0    1  162   16    1    4  162    0  ...    1    7    0   
1        58   18    0    3   23    7   16   40  131   73  ...    0   36   95   
2        43   74   25   13    8    2    0    1  100  104  ...    1   25   12   
3       127   30    1    0    2    8   24   37   72   17  ...   14   98   73   
4        10    0    0    0  150   12    0    1  150    4  ...    0    2    0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
652736   14   46   23   11    1    0    0    0  107  115  ...    6    5    0   
652737   20   33   53   13    0    1    0    3   50   17  ...    0    5   37   
652738   21   15    4    0    0   24  135   82   15   18  ...    0    0    0   
652739    0    1    0    0    0    0    1    0    7  134  ...   28   73    1   
652740    7   22   59   10    9    8    1    4    8   64  ...    1    0    0   

        121  122  123  124  125  126  127  
0         0    2   32   23    2    0    0  
1        23    1    1   29   13    2   11  
2         7    3    2    2    2    8   27  
3        28    4    1    2    5   19   41  
4         0    1   36  122    1    0    0  
...     ...  ...  ...  ...  ...  ...  ...  
652736   78  110   33   14    3    0    0  
652737   52    0    0    0    0    0    3  
652738    0    0    0    0    0    0    0  
652739    1    7   18    2   10   47   11  
652740    1    0    0    0    0    0    0  

[652741 rows x 128 columns]

# Negative Images

In [170]:
i=0
for filename in os.listdir(folder2):
    try:
        path=os.path.join(folder2,filename)
        a=cv2.imread(path)

        #resize image
        resize=(180,230)
        img=cv2.resize(a,resize)
    except Exception as e:
        print(str(e))
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv(r'C:\ICTS\ICTS DATASET\pn1e.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (109, 128)
descriptor shape  1  :  (123, 128)
descriptor shape  2  :  (120, 128)
descriptor shape  3  :  (118, 128)
descriptor shape  4  :  (194, 128)
descriptor shape  5  :  (202, 128)
descriptor shape  6  :  (189, 128)
descriptor shape  7  :  (182, 128)
descriptor shape  8  :  (139, 128)
descriptor shape  9  :  (94, 128)
descriptor shape  10  :  (93, 128)
descriptor shape  11  :  (81, 128)
descriptor shape  12  :  (85, 128)
descriptor shape  13  :  (185, 128)
descriptor shape  14  :  (115, 128)
descriptor shape  15  :  (108, 128)
descriptor shape  16  :  (112, 128)
descriptor shape  17  :  (100, 128)
descriptor shape  18  :  (107, 128)
descriptor shape  19  :  (140, 128)
descriptor shape  20  :  (142, 128)
descriptor shape  21  :  (112, 128)
descriptor shape  22  :  (88, 128)
descriptor shape  23  :  (122, 128)
descriptor shape  24  :  (223, 128)
descriptor shape  25  :  (98, 128)
descriptor shape  26  :  (131, 128)
descriptor shape  27  :  (110, 128)
descript

descriptor shape  233  :  (198, 128)
descriptor shape  234  :  (169, 128)
descriptor shape  235  :  (135, 128)
descriptor shape  236  :  (310, 128)
descriptor shape  237  :  (265, 128)
descriptor shape  238  :  (249, 128)
descriptor shape  239  :  (303, 128)
descriptor shape  240  :  (182, 128)
descriptor shape  241  :  (126, 128)
descriptor shape  242  :  (277, 128)
descriptor shape  243  :  (196, 128)
descriptor shape  244  :  (171, 128)
descriptor shape  245  :  (200, 128)
descriptor shape  246  :  (129, 128)
descriptor shape  247  :  (203, 128)
descriptor shape  248  :  (136, 128)
descriptor shape  249  :  (83, 128)
descriptor shape  250  :  (450, 128)
descriptor shape  251  :  (506, 128)
descriptor shape  252  :  (447, 128)
descriptor shape  253  :  (256, 128)
descriptor shape  254  :  (358, 128)
descriptor shape  255  :  (105, 128)
descriptor shape  256  :  (62, 128)
descriptor shape  257  :  (124, 128)
descriptor shape  258  :  (382, 128)
descriptor shape  259  :  (328, 128)
des

descriptor shape  457  :  (142, 128)
descriptor shape  458  :  (91, 128)
descriptor shape  459  :  (343, 128)
descriptor shape  460  :  (359, 128)
descriptor shape  461  :  (376, 128)
descriptor shape  462  :  (283, 128)
descriptor shape  463  :  (279, 128)
descriptor shape  464  :  (136, 128)
descriptor shape  465  :  (205, 128)
descriptor shape  466  :  (312, 128)
descriptor shape  467  :  (365, 128)
descriptor shape  468  :  (151, 128)
descriptor shape  469  :  (177, 128)
descriptor shape  470  :  (174, 128)
descriptor shape  471  :  (255, 128)
descriptor shape  472  :  (196, 128)
descriptor shape  473  :  (285, 128)
descriptor shape  474  :  (508, 128)
descriptor shape  475  :  (133, 128)
descriptor shape  476  :  (192, 128)
descriptor shape  477  :  (205, 128)
descriptor shape  478  :  (199, 128)
descriptor shape  479  :  (221, 128)
descriptor shape  480  :  (162, 128)
descriptor shape  481  :  (390, 128)
descriptor shape  482  :  (239, 128)
descriptor shape  483  :  (110, 128)
de

descriptor shape  684  :  (316, 128)
descriptor shape  685  :  (342, 128)
descriptor shape  686  :  (370, 128)
descriptor shape  687  :  (464, 128)
descriptor shape  688  :  (340, 128)
descriptor shape  689  :  (412, 128)
descriptor shape  690  :  (241, 128)
descriptor shape  691  :  (215, 128)
descriptor shape  692  :  (200, 128)
descriptor shape  693  :  (305, 128)
descriptor shape  694  :  (168, 128)
descriptor shape  695  :  (206, 128)
descriptor shape  696  :  (72, 128)
descriptor shape  697  :  (171, 128)
descriptor shape  698  :  (458, 128)
descriptor shape  699  :  (258, 128)
descriptor shape  700  :  (395, 128)
descriptor shape  701  :  (231, 128)
descriptor shape  702  :  (340, 128)
descriptor shape  703  :  (428, 128)
descriptor shape  704  :  (319, 128)
descriptor shape  705  :  (321, 128)
descriptor shape  706  :  (452, 128)
descriptor shape  707  :  (114, 128)
descriptor shape  708  :  (122, 128)
descriptor shape  709  :  (230, 128)
descriptor shape  710  :  (139, 128)
de

descriptor shape  912  :  (196, 128)
descriptor shape  913  :  (230, 128)
descriptor shape  914  :  (248, 128)
descriptor shape  915  :  (240, 128)
descriptor shape  916  :  (253, 128)
descriptor shape  917  :  (242, 128)
descriptor shape  918  :  (216, 128)
descriptor shape  919  :  (268, 128)
descriptor shape  920  :  (262, 128)
descriptor shape  921  :  (180, 128)
descriptor shape  922  :  (274, 128)
descriptor shape  923  :  (189, 128)
descriptor shape  924  :  (226, 128)
descriptor shape  925  :  (244, 128)
descriptor shape  926  :  (226, 128)
descriptor shape  927  :  (244, 128)
descriptor shape  928  :  (342, 128)
descriptor shape  929  :  (335, 128)
descriptor shape  930  :  (272, 128)
descriptor shape  931  :  (231, 128)
descriptor shape  932  :  (229, 128)
descriptor shape  933  :  (227, 128)
descriptor shape  934  :  (189, 128)
descriptor shape  935  :  (306, 128)
descriptor shape  936  :  (304, 128)
descriptor shape  937  :  (296, 128)
descriptor shape  938  :  (264, 128)
d

descriptor shape  1143  :  (126, 128)
descriptor shape  1144  :  (125, 128)
descriptor shape  1145  :  (138, 128)
descriptor shape  1146  :  (79, 128)
descriptor shape  1147  :  (126, 128)
descriptor shape  1148  :  (138, 128)
descriptor shape  1149  :  (126, 128)
descriptor shape  1150  :  (135, 128)
descriptor shape  1151  :  (121, 128)
descriptor shape  1152  :  (133, 128)
descriptor shape  1153  :  (130, 128)
descriptor shape  1154  :  (148, 128)
descriptor shape  1155  :  (132, 128)
descriptor shape  1156  :  (164, 128)
descriptor shape  1157  :  (88, 128)
descriptor shape  1158  :  (159, 128)
descriptor shape  1159  :  (149, 128)
descriptor shape  1160  :  (150, 128)
descriptor shape  1161  :  (161, 128)
descriptor shape  1162  :  (142, 128)
descriptor shape  1163  :  (145, 128)
descriptor shape  1164  :  (129, 128)
descriptor shape  1165  :  (148, 128)
descriptor shape  1166  :  (176, 128)
descriptor shape  1167  :  (183, 128)
descriptor shape  1168  :  (80, 128)
descriptor shap

descriptor shape  1362  :  (151, 128)
descriptor shape  1363  :  (236, 128)
descriptor shape  1364  :  (191, 128)
descriptor shape  1365  :  (120, 128)
descriptor shape  1366  :  (215, 128)
descriptor shape  1367  :  (198, 128)
descriptor shape  1368  :  (136, 128)
descriptor shape  1369  :  (121, 128)
descriptor shape  1370  :  (162, 128)
descriptor shape  1371  :  (309, 128)
descriptor shape  1372  :  (168, 128)
descriptor shape  1373  :  (249, 128)
descriptor shape  1374  :  (140, 128)
descriptor shape  1375  :  (309, 128)
descriptor shape  1376  :  (345, 128)
descriptor shape  1377  :  (132, 128)
descriptor shape  1378  :  (144, 128)
descriptor shape  1379  :  (111, 128)
descriptor shape  1380  :  (160, 128)
descriptor shape  1381  :  (194, 128)
descriptor shape  1382  :  (373, 128)
descriptor shape  1383  :  (370, 128)
descriptor shape  1384  :  (346, 128)
descriptor shape  1385  :  (129, 128)
descriptor shape  1386  :  (302, 128)
descriptor shape  1387  :  (130, 128)
descriptor s

descriptor shape  1578  :  (300, 128)
descriptor shape  1579  :  (183, 128)
descriptor shape  1580  :  (100, 128)
descriptor shape  1581  :  (170, 128)
descriptor shape  1582  :  (386, 128)
descriptor shape  1583  :  (274, 128)
descriptor shape  1584  :  (84, 128)
descriptor shape  1585  :  (298, 128)
descriptor shape  1586  :  (514, 128)
descriptor shape  1587  :  (513, 128)
descriptor shape  1588  :  (333, 128)
descriptor shape  1589  :  (122, 128)
descriptor shape  1590  :  (176, 128)
descriptor shape  1591  :  (196, 128)
descriptor shape  1592  :  (460, 128)
descriptor shape  1593  :  (415, 128)
descriptor shape  1594  :  (318, 128)
descriptor shape  1595  :  (595, 128)
descriptor shape  1596  :  (556, 128)
descriptor shape  1597  :  (127, 128)
descriptor shape  1598  :  (374, 128)
descriptor shape  1599  :  (175, 128)
descriptor shape  1600  :  (328, 128)
descriptor shape  1601  :  (187, 128)
descriptor shape  1602  :  (381, 128)
descriptor shape  1603  :  (174, 128)
descriptor sh

descriptor shape  1795  :  (212, 128)
descriptor shape  1796  :  (294, 128)
descriptor shape  1797  :  (253, 128)
descriptor shape  1798  :  (216, 128)
descriptor shape  1799  :  (360, 128)
descriptor shape  1800  :  (373, 128)
descriptor shape  1801  :  (186, 128)
descriptor shape  1802  :  (160, 128)
descriptor shape  1803  :  (16, 128)
descriptor shape  1804  :  (317, 128)
descriptor shape  1805  :  (184, 128)
descriptor shape  1806  :  (111, 128)
descriptor shape  1807  :  (147, 128)
descriptor shape  1808  :  (116, 128)
descriptor shape  1809  :  (308, 128)
descriptor shape  1810  :  (73, 128)
descriptor shape  1811  :  (183, 128)
descriptor shape  1812  :  (151, 128)
descriptor shape  1813  :  (145, 128)
descriptor shape  1814  :  (216, 128)
descriptor shape  1815  :  (175, 128)
descriptor shape  1816  :  (125, 128)
descriptor shape  1817  :  (377, 128)
descriptor shape  1818  :  (430, 128)
descriptor shape  1819  :  (257, 128)
descriptor shape  1820  :  (361, 128)
descriptor sha

descriptor shape  2024  :  (120, 128)
descriptor shape  2025  :  (136, 128)
descriptor shape  2026  :  (137, 128)
descriptor shape  2027  :  (139, 128)
descriptor shape  2028  :  (226, 128)
descriptor shape  2029  :  (202, 128)
descriptor shape  2030  :  (183, 128)
descriptor shape  2031  :  (225, 128)
descriptor shape  2032  :  (273, 128)
descriptor shape  2033  :  (302, 128)
descriptor shape  2034  :  (181, 128)
descriptor shape  2035  :  (287, 128)
descriptor shape  2036  :  (295, 128)
descriptor shape  2037  :  (264, 128)
descriptor shape  2038  :  (327, 128)
descriptor shape  2039  :  (305, 128)
descriptor shape  2040  :  (278, 128)
descriptor shape  2041  :  (294, 128)
descriptor shape  2042  :  (446, 128)
descriptor shape  2043  :  (423, 128)
descriptor shape  2044  :  (382, 128)
descriptor shape  2045  :  (175, 128)
descriptor shape  2046  :  (137, 128)
descriptor shape  2047  :  (157, 128)
descriptor shape  2048  :  (162, 128)
descriptor shape  2049  :  (191, 128)
descriptor s

descriptor shape  2248  :  (574, 128)
descriptor shape  2249  :  (594, 128)
descriptor shape  2250  :  (319, 128)
descriptor shape  2251  :  (467, 128)
descriptor shape  2252  :  (124, 128)
descriptor shape  2253  :  (62, 128)
descriptor shape  2254  :  (241, 128)
descriptor shape  2255  :  (352, 128)
descriptor shape  2256  :  (451, 128)
descriptor shape  2257  :  (329, 128)
descriptor shape  2258  :  (119, 128)
descriptor shape  2259  :  (453, 128)
descriptor shape  2260  :  (143, 128)
descriptor shape  2261  :  (136, 128)
descriptor shape  2262  :  (443, 128)
descriptor shape  2263  :  (132, 128)
descriptor shape  2264  :  (83, 128)
descriptor shape  2265  :  (304, 128)
descriptor shape  2266  :  (220, 128)
descriptor shape  2267  :  (347, 128)
descriptor shape  2268  :  (406, 128)
descriptor shape  2269  :  (200, 128)
descriptor shape  2270  :  (221, 128)
descriptor shape  2271  :  (371, 128)
descriptor shape  2272  :  (148, 128)
descriptor shape  2273  :  (381, 128)
descriptor sha

descriptor shape  2467  :  (148, 128)
descriptor shape  2468  :  (281, 128)
descriptor shape  2469  :  (201, 128)
descriptor shape  2470  :  (320, 128)
descriptor shape  2471  :  (586, 128)
descriptor shape  2472  :  (129, 128)
descriptor shape  2473  :  (208, 128)
descriptor shape  2474  :  (185, 128)
descriptor shape  2475  :  (230, 128)
descriptor shape  2476  :  (128, 128)
descriptor shape  2477  :  (156, 128)
descriptor shape  2478  :  (459, 128)
descriptor shape  2479  :  (278, 128)
descriptor shape  2480  :  (109, 128)
descriptor shape  2481  :  (299, 128)
descriptor shape  2482  :  (226, 128)
descriptor shape  2483  :  (240, 128)
descriptor shape  2484  :  (244, 128)
descriptor shape  2485  :  (77, 128)
descriptor shape  2486  :  (319, 128)
descriptor shape  2487  :  (65, 128)
descriptor shape  2488  :  (338, 128)
descriptor shape  2489  :  (192, 128)
descriptor shape  2490  :  (456, 128)
descriptor shape  2491  :  (190, 128)
descriptor shape  2492  :  (215, 128)
descriptor sha

descriptor shape  2689  :  (248, 128)
descriptor shape  2690  :  (186, 128)
descriptor shape  2691  :  (359, 128)
descriptor shape  2692  :  (208, 128)
descriptor shape  2693  :  (198, 128)
descriptor shape  2694  :  (88, 128)
descriptor shape  2695  :  (219, 128)
descriptor shape  2696  :  (473, 128)
descriptor shape  2697  :  (252, 128)
descriptor shape  2698  :  (394, 128)
descriptor shape  2699  :  (117, 128)
descriptor shape  2700  :  (427, 128)
descriptor shape  2701  :  (446, 128)
descriptor shape  2702  :  (354, 128)
descriptor shape  2703  :  (374, 128)
descriptor shape  2704  :  (483, 128)
descriptor shape  2705  :  (125, 128)
descriptor shape  2706  :  (136, 128)
descriptor shape  2707  :  (257, 128)
descriptor shape  2708  :  (158, 128)
descriptor shape  2709  :  (288, 128)
descriptor shape  2710  :  (128, 128)
descriptor shape  2711  :  (155, 128)
descriptor shape  2712  :  (328, 128)
descriptor shape  2713  :  (73, 128)
descriptor shape  2714  :  (393, 128)
descriptor sha

descriptor shape  2911  :  (189, 128)
descriptor shape  2912  :  (143, 128)
descriptor shape  2913  :  (200, 128)
descriptor shape  2914  :  (248, 128)
descriptor shape  2915  :  (214, 128)
descriptor shape  2916  :  (218, 128)
descriptor shape  2917  :  (185, 128)
descriptor shape  2918  :  (231, 128)
descriptor shape  2919  :  (283, 128)
descriptor shape  2920  :  (243, 128)
descriptor shape  2921  :  (171, 128)
descriptor shape  2922  :  (255, 128)
descriptor shape  2923  :  (111, 128)
descriptor shape  2924  :  (221, 128)
descriptor shape  2925  :  (224, 128)
descriptor shape  2926  :  (206, 128)
descriptor shape  2927  :  (224, 128)
descriptor shape  2928  :  (286, 128)
descriptor shape  2929  :  (321, 128)
descriptor shape  2930  :  (265, 128)
descriptor shape  2931  :  (237, 128)
descriptor shape  2932  :  (254, 128)
descriptor shape  2933  :  (241, 128)
descriptor shape  2934  :  (94, 128)
descriptor shape  2935  :  (270, 128)
descriptor shape  2936  :  (277, 128)
descriptor sh

In [171]:
data2= pd.read_csv(r'C:\ICTS\ICTS DATASET\pn1e.csv',header=None,dtype='uint8')
data2=data2.astype(np.uint8)
data2

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0        45   26    8    1    0    0    0    2  182   33  ...    0    2    0   
1        23    0    0    1    4    2    0   11  153    0  ...    1    8    2   
2        71    5    0    0    0    1    1    7  153   21  ...    0    0    1   
3        25   33   26   47   15    0    0    0  148  110  ...    0   40  107   
4       135   77    7    4    0    1    4   11   83   61  ...    0   34   31   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
692114    7    0    0    0    7    7    3    8  110    9  ...    0    0  112   
692115   24    3    0    0    1    0    0    6  125   60  ...   23   12   26   
692116   41    2    0    0    0    0    0    1  214   12  ...    7   32    6   
692117   79   68    0    0    0    0    0    0  154   56  ...    0    0    0   
692118   28    5    0    0    6   13   34   75   58   32  ...   23  134   14   

        121  122  123  124  125  126  127  
0         0    0    0    0    0    0    0  
1         4    2    9   20    0    0    0  
2         2    0    4   84    3    0    0  
3         0    0    1   11    2    1   35  
4         0    0    5    7    0    0   20  
...     ...  ...  ...  ...  ...  ...  ...  
692114   20    5   12   64    6    1   10  
692115   33    3    2    3   30   22    4  
692116    1    0    2    5    0    5   13  
692117    0    2   24   21    0    0    0  
692118    0    0   41   38    1    6  117  

[692119 rows x 128 columns]

# Appending all data

In [172]:
data=data1.append(data2)

In [173]:
csv_data=data.to_csv(r'C:\ICTS\ICTS DATASET\Sift_Finalp1e.csv', mode='a', header=False,index=False)

In [174]:
data

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0        12    0    0    1  162   16    1    4  162    0  ...    1    7    0   
1        58   18    0    3   23    7   16   40  131   73  ...    0   36   95   
2        43   74   25   13    8    2    0    1  100  104  ...    1   25   12   
3       127   30    1    0    2    8   24   37   72   17  ...   14   98   73   
4        10    0    0    0  150   12    0    1  150    4  ...    0    2    0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
692114    7    0    0    0    7    7    3    8  110    9  ...    0    0  112   
692115   24    3    0    0    1    0    0    6  125   60  ...   23   12   26   
692116   41    2    0    0    0    0    0    1  214   12  ...    7   32    6   
692117   79   68    0    0    0    0    0    0  154   56  ...    0    0    0   
692118   28    5    0    0    6   13   34   75   58   32  ...   23  134   14   

        121  122  123  124  125  126  127  
0         0    2   32   23    2    0    0  
1        23    1    1   29   13    2   11  
2         7    3    2    2    2    8   27  
3        28    4    1    2    5   19   41  
4         0    1   36  122    1    0    0  
...     ...  ...  ...  ...  ...  ...  ...  
692114   20    5   12   64    6    1   10  
692115   33    3    2    3   30   22    4  
692116    1    0    2    5    0    5   13  
692117    0    2   24   21    0    0    0  
692118    0    0   41   38    1    6  117  

[1344860 rows x 128 columns]

# K means clustering

In [175]:
kmeans = KMeans(n_clusters=5)
kmeans.fit(data)
import pickle
# save the model to disk
filename = 'Kmeans_CL_5_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [176]:
hist=np.histogram(kmeans.labels_,bins=[0,1,2,3,4,5])


print('histogram of trained kmeans')
print(hist,"\n")

histogram of trained kmeans
(array([297774, 178955, 234521, 292253, 341357], dtype=int64), array([0, 1, 2, 3, 4, 5])) 



# K means prediction forRightCurve class

In [177]:
#performing kmeans prediction of the entire Staircase dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder1):
    try:
        #path
        path=os.path.join(folder1,filename)
        a=cv2.imread(path)

        #resize image
        resize=(280,430)
        img=cv2.resize(a,resize)
    except Exception as e:
        print(str(e))
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans.predict(array_double)
    
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv(r'C:\ICTS\ICTS DATASET\FinalStrp1e.csv', mode='a',header=False,index=False)

# K means prediction for negative images

In [178]:
#performing kmeans prediction of the entire Non_Staircase dataset with the pretrained kmeans model

#initialising i=1; as its the 2nd class
i=1
data=[]
k=0
for filename in os.listdir(folder2):
    try:
        path=os.path.join(folder2,filename)
        a=cv2.imread(path)
        resize=(280,430)
        img=cv2.resize(a,resize)
    except Exception as e:
        print(str(e))
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    sift = cv2.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float' but got 'double', in order to avoid this dtype=np.double
    try:
        array_double = np.array(out, dtype=np.double)
        a=kmeans.predict(array_double)
    except ValueError as v:
        pass
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv(r'C:\ICTS\ICTS DATASET\FinalNstrp1e.csv', mode='a',header=False,index=False)

# Predicted data (RightCurve)

In [239]:
#Displaying the kmeans predicted data
print("RightCurve")
dat1= pd.read_csv(r'C:\ICTS\ICTS DATASET\FinalStrp1e.csv',header=None)
print(dat1)

RightCurve
        0    1    2    3    4  5
0     163   83  118  126  182  0
1     172   79  129  145  209  0
2     410  191  278  101  346  0
3      86   67  125  158   93  0
4      93   80  118  157   93  0
...   ...  ...  ...  ...  ... ..
2995  275  149  210  129  275  0
2996  256  151  201  131  291  0
2997  301  158  225  132  305  0
2998  305  183  287  129  316  0
2999  346  210  289  109  415  0

[3000 rows x 6 columns]


# Predicted data (Negative images)

In [240]:
print("Non-RightCurve")
dat2= pd.read_csv(r'C:\ICTS\ICTS DATASET\FinalNstrp1e.csv',header=None)
print(dat2)

Non-RightCurve
        0   1   2    3    4  5
0      55  52  20   54   54  1
1     102  91  73   95  119  1
2      44  41  28  119   33  1
3      28  51  35  145   21  1
4      78  72  69  177   78  1
...   ...  ..  ..  ...  ... ..
2995   16  16  13  118   16  1
2996   23  37  28  161   34  1
2997   34  35  27  142   23  1
2998   24  29  28  131   17  1
2999   14  35  40  155   11  1

[3000 rows x 6 columns]


In [181]:
#appending All classes into 1 csv file

A=dat1.append(dat2)

csv_data=A.to_csv('C:\ICTS\ICTS DATASET\FinalFVp1e.csv', mode='a',header=False,index=False)

In [182]:
A

0    1    2    3    4  5
0     163   83  118  126  182  0
1     172   79  129  145  209  0
2     410  191  278  101  346  0
3      86   67  125  158   93  0
4      93   80  118  157   93  0
...   ...  ...  ...  ...  ... ..
2995   16   16   13  118   16  1
2996   23   37   28  161   34  1
2997   34   35   27  142   23  1
2998   24   29   28  131   17  1
2999   14   35   40  155   11  1

[6000 rows x 6 columns]

In [183]:
x = A.iloc[:,0:5].values

In [184]:
x

array([[163,  83, 118, 126, 182],
       [172,  79, 129, 145, 209],
       [410, 191, 278, 101, 346],
       ...,
       [ 34,  35,  27, 142,  23],
       [ 24,  29,  28, 131,  17],
       [ 14,  35,  40, 155,  11]], dtype=int64)

In [185]:
y = A.iloc[:,5].values

In [186]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

# Using StandardScaler

In [187]:
from sklearn.preprocessing import StandardScaler
DhoniS = StandardScaler()
Dhoni = DhoniS.fit_transform(x)

In [188]:
Dhoni

array([[ 0.31859294, -0.185997  , -0.01465873, -0.03506006,  0.40827195],
       [ 0.4206994 , -0.25173387,  0.12680588,  0.33125349,  0.69303314],
       [ 3.12084788,  1.58889853,  2.04300837, -0.51705158,  2.13793247],
       ...,
       [-1.14493292, -0.97483946, -1.1849569 ,  0.27341451, -1.26865502],
       [-1.25838454, -1.07344476, -1.17209648,  0.06133824, -1.33193528],
       [-1.37183615, -0.97483946, -1.01777145,  0.52405009, -1.39521554]])

# Principal Component Analysis

In [189]:
from sklearn.decomposition import PCA

In [190]:
pca = PCA(n_components=None)
pca.fit(Dhoni)

PCA()

In [191]:
Bhumi = pca.transform(Dhoni)

In [192]:
Bhumi

array([[ 0.23637679, -0.35734558, -0.34006332,  0.05534736, -0.04416081],
       [ 0.55054543, -0.21952634, -0.66073237,  0.173033  , -0.16929761],
       [ 4.15966596, -1.86002911,  0.19976189,  0.16767576,  0.66762391],
       ...,
       [-2.14062184,  0.80448016, -0.31943627, -0.06464429,  0.11780777],
       [-2.31925392,  0.68340157, -0.19033617,  0.01471739,  0.0708414 ],
       [-2.15998595,  1.158698  , -0.27163037,  0.08246555,  0.02561309]])

In [193]:
Bhumi = pd.DataFrame(Bhumi)

In [194]:
Bhumi

0         1         2         3         4
0     0.236377 -0.357346 -0.340063  0.055347 -0.044161
1     0.550545 -0.219526 -0.660732  0.173033 -0.169298
2     4.159666 -1.860029  0.199762  0.167676  0.667624
3    -0.544178  0.789659 -0.156148  0.433896 -0.052944
4    -0.453324  0.783670 -0.093041  0.225839  0.016815
...        ...       ...       ...       ...       ...
5995 -2.631980  0.452593 -0.213087  0.008803  0.021836
5996 -2.030951  1.104789 -0.506677 -0.083716 -0.045988
5997 -2.140622  0.804480 -0.319436 -0.064644  0.117808
5998 -2.319254  0.683402 -0.190336  0.014717  0.070841
5999 -2.159986  1.158698 -0.271630  0.082466  0.025613

[6000 rows x 5 columns]

In [195]:
Bhumi.shape

(6000, 5)

In [196]:
print(pca.explained_variance_ratio_) 

[0.68023785 0.21117023 0.07685619 0.01824939 0.01348635]


In [197]:
pca = PCA(n_components=3)
pca.fit(Dhoni)

PCA(n_components=3)

In [198]:
# save the model to disk
filename = 'PCA_3_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [199]:
Bhumi = pca.transform(Dhoni)

In [200]:
Bhumi

array([[ 0.23637679, -0.35734558, -0.34006332],
       [ 0.55054543, -0.21952634, -0.66073237],
       [ 4.15966596, -1.86002911,  0.19976189],
       ...,
       [-2.14062184,  0.80448016, -0.31943627],
       [-2.31925392,  0.68340157, -0.19033617],
       [-2.15998595,  1.158698  , -0.27163037]])

In [201]:
Bhumi.shape

(6000, 3)

In [202]:
print(pca.explained_variance_ratio_) 

[0.68023785 0.21117023 0.07685619]


In [203]:
Bhumi = pd.DataFrame(Bhumi)

In [204]:
Bhumi

0         1         2
0     0.236377 -0.357346 -0.340063
1     0.550545 -0.219526 -0.660732
2     4.159666 -1.860029  0.199762
3    -0.544178  0.789659 -0.156148
4    -0.453324  0.783670 -0.093041
...        ...       ...       ...
5995 -2.631980  0.452593 -0.213087
5996 -2.030951  1.104789 -0.506677
5997 -2.140622  0.804480 -0.319436
5998 -2.319254  0.683402 -0.190336
5999 -2.159986  1.158698 -0.271630

[6000 rows x 3 columns]

In [205]:
B=pd.concat([Bhumi, pd.DataFrame(y)],axis=1)

In [206]:
B

0         1         2  0
0     0.236377 -0.357346 -0.340063  0
1     0.550545 -0.219526 -0.660732  0
2     4.159666 -1.860029  0.199762  0
3    -0.544178  0.789659 -0.156148  0
4    -0.453324  0.783670 -0.093041  0
...        ...       ...       ... ..
5995 -2.631980  0.452593 -0.213087  1
5996 -2.030951  1.104789 -0.506677  1
5997 -2.140622  0.804480 -0.319436  1
5998 -2.319254  0.683402 -0.190336  1
5999 -2.159986  1.158698 -0.271630  1

[6000 rows x 4 columns]

In [207]:
csv_data=B.to_csv('C:\ICTS\ICTS DATASET\FinalPCAFVp1e.csv', mode='a',header=False,index=False)

# Training , Testing and Classification

In [208]:
data= pd.read_csv(r'C:\ICTS\ICTS DATASET\FinalPCAFVp1e.csv',header=None)

data

0         1         2  3
0     0.236377 -0.357346 -0.340063  0
1     0.550545 -0.219526 -0.660732  0
2     4.159666 -1.860029  0.199762  0
3    -0.544178  0.789659 -0.156148  0
4    -0.453324  0.783670 -0.093041  0
...        ...       ...       ... ..
5995 -2.631980  0.452593 -0.213087  1
5996 -2.030951  1.104789 -0.506677  1
5997 -2.140622  0.804480 -0.319436  1
5998 -2.319254  0.683402 -0.190336  1
5999 -2.159986  1.158698 -0.271630  1

[6000 rows x 4 columns]

In [209]:
#assigning x the columns from 1 to 128 for training
x = data.iloc[:,0:3].values
print("X values")
print(x)

#assigning y with the column "Class" as target variable
y = data.iloc[:,3]
print("Y values")
print(y)

X values
[[ 0.23637679 -0.35734558 -0.34006332]
 [ 0.55054543 -0.21952634 -0.66073237]
 [ 4.15966596 -1.86002911  0.19976189]
 ...
 [-2.14062184  0.80448016 -0.31943627]
 [-2.31925392  0.68340157 -0.19033617]
 [-2.15998595  1.158698   -0.27163037]]
Y values
0       0
1       0
2       0
3       0
4       0
       ..
5995    1
5996    1
5997    1
5998    1
5999    1
Name: 3, Length: 6000, dtype: int64


In [210]:
#Dataset split into train and test with 80% Training and 20% Testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.10, random_state=0)

# Decision Tree

In [211]:
#Decision Tree Classifier
from sklearn.metrics import accuracy_score
#Assign model with Decision Tree classifier
model1 = DecisionTreeClassifier(max_depth=13)
filename = 'model1.sav'
pickle.dump(kmeans, open(filename, 'wb'))
#training the model with the Training Variables 
model1.fit(x_train, y_train)
#predicting the traget variable using testing variables
y_pred1 = model1.predict(x_test)

#Results
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred1))
print("Decision Tree Results")
print("Decision Tree Accuracy: ",accuracy_score(y_test, y_pred1)*100,"%")

print("Decision Tree Results")
# print('\nTraining Accuracy: {:.2f}\n'.format(accuracy_score(y_train, y_pred1)))
print('\nTesting Accuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred1)))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred1, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred1, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred1, average='weighted')))

print('\nClassification Report\n')
print(classification_report(y_test, y_pred1, target_names=['Class 1', 'Class 2']))

[[219  62]
 [ 87 232]]
Decision Tree Results
Decision Tree Accuracy:  75.16666666666667 %
Decision Tree Results

Testing Accuracy: 0.75

Weighted Precision: 0.75
Weighted Recall: 0.75
Weighted F1-score: 0.75

Classification Report

              precision    recall  f1-score   support

     Class 1       0.72      0.78      0.75       281
     Class 2       0.79      0.73      0.76       319

    accuracy                           0.75       600
   macro avg       0.75      0.75      0.75       600
weighted avg       0.75      0.75      0.75       600



In [212]:
#Recognition &Validation
#Assigning path with any any class image
data=[]
path=r"C:\ICTS\ICTS DATASET\Positive images\RightCurve2\rightcurve159.jpg"


#Repeated the process of image pre-processing and feature extraction
try:
    a=cv2.imread(path)
    resize=(280,430)

    #resize image
    img=cv2.resize(a,resize)
except Exception as e:
    print("corrupt Img")
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

#initialise sift descriptor
sift = cv2.SIFT_create()
keypoints, descriptors = sift.detectAndCompute(gray, None)

#convert the descriptor array into a dataframe format
out=pd.DataFrame(descriptors)
print("Descriptor Shape:",out.shape)

#initialise Kmeans and create 5 clusters


#train the model for the features i.e. for all elements in the Dataframe
array_double = np.array(out, dtype=np.double)
a=kmeans.predict(array_double)

#get the values of the histogram for one image only for 5 clusters i.e. in 5 bins
#kmeans.labels_ give us the label vlaue of the feature that its clustered into
#hist will give the hostogram for all those vlaues
hist=np.histogram(a,bins=[0,1,2,3,4,5])

#append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
data.append(hist[0])

Output = pd.DataFrame(data)
print("Histogram:\n",Output)

Descriptor Shape: (395, 128)
Histogram:
     0   1   2   3    4
0  97  32  67  70  129


In [213]:
from sklearn.preprocessing import StandardScaler
MuktaS = StandardScaler()
Mukta = MuktaS.fit_transform(Output)

In [214]:
Mukta

array([[0., 0., 0., 0., 0.]])

In [215]:
Mukta.shape

(1, 5)

In [216]:
MB = pca.transform(Mukta)

In [217]:
MB.shape

(1, 3)

In [218]:
MB

array([[ 3.06799890e-17,  1.82180632e-18, -4.78146551e-17]])

In [219]:
#prediction
y_pred1 = model1.predict(MB)

#prints the prediction of the class
print(y_pred1)

[0]


# SVC

In [220]:
from sklearn.svm import SVC
DhoniSVM_LK = SVC(kernel='rbf')
Dhoni_LK = DhoniSVM_LK.fit(x_train, y_train)

In [221]:
filename = 'SVC_RBF_PCA_3.sav'
pickle.dump(Dhoni_LK, open(filename, 'wb'))

In [222]:
Dhoni_LK

SVC()

In [223]:
y_pred_LK = Dhoni_LK.predict(x_test)

In [224]:
y_pred_LK

array([1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [225]:
from sklearn.metrics import confusion_matrix

In [226]:
confusion_matrix(y_test, y_pred_LK)

array([[220,  61],
       [ 77, 242]], dtype=int64)

In [227]:
from sklearn.metrics import accuracy_score

In [228]:
accuracy_score(y_test, y_pred_LK)

0.77

In [229]:
y_pred1 = model1.predict(MB)



In [230]:
#print(y_pred1)
print("SVC Results")
#print('\nTraining Accuracy: {:.2f}\n'.format(accuracy_score(y_train, y_pred_LK)))
print('\nTesting Accuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred_LK)))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred_LK, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred_LK, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred_LK, average='weighted')))

print('\nClassification Report\n')
print(classification_report(y_test, y_pred_LK, target_names=['Class 1', 'Class 2']))

SVC Results

Testing Accuracy: 0.77

Weighted Precision: 0.77
Weighted Recall: 0.77
Weighted F1-score: 0.77

Classification Report

              precision    recall  f1-score   support

     Class 1       0.74      0.78      0.76       281
     Class 2       0.80      0.76      0.78       319

    accuracy                           0.77       600
   macro avg       0.77      0.77      0.77       600
weighted avg       0.77      0.77      0.77       600



# Random Forest 

In [231]:
#Random Forest Classifier
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
import pickle
model_rf = RandomForestClassifier(n_estimators = 500)
filename = 'model_rf.sav'
pickle.dump(kmeans, open(filename, 'wb'))
model_rf1 =model_rf.fit(x_train, y_train)
y_pred_rf = model_rf1.predict(x_test)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred_rf)
print("Random Forest Accuracy: ",accuracy_score(y_test, y_pred_rf)*100,"%")

Random Forest Accuracy:  78.5 %


In [232]:
#print(y_pred1)
print("Random Forest Results")
#print('\nTraining Accuracy: {:.2f}\n'.format(accuracy_score(y_train, y_pred1)))
print('\nTesting Accuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred_rf)))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred_rf, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred_rf, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred_rf, average='weighted')))

print('\nClassification Report\n')
print(classification_report(y_test, y_pred_rf, target_names=['Class 1', 'Class 2']))

Random Forest Results

Testing Accuracy: 0.79

Weighted Precision: 0.79
Weighted Recall: 0.79
Weighted F1-score: 0.79

Classification Report

              precision    recall  f1-score   support

     Class 1       0.77      0.78      0.77       281
     Class 2       0.80      0.79      0.80       319

    accuracy                           0.79       600
   macro avg       0.78      0.78      0.78       600
weighted avg       0.79      0.79      0.79       600



# SVM

In [233]:
# SVM
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
import pickle
SVM_LK = SVC(kernel='rbf')
LK = SVM_LK.fit(x_train, y_train)
filename = 'SVC_RBF_PCA_3.sav'
pickle.dump(LK, open(filename, 'wb'))
y_pred_LK = LK.predict(x_test)
print(accuracy_score(y_test, y_pred_LK))

0.77


In [234]:
#print(y_pred1)
print("SVM Results")
#print('\nTraining Accuracy: {:.2f}\n'.format(accuracy_score(y_train, y_pred1)))
print('\nTesting Accuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred_LK)))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred_LK, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred_LK, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred_LK, average='weighted')))

print('\nClassification Report\n')
print(classification_report(y_test, y_pred_LK, target_names=['Class 1', 'Class 2']))

SVM Results

Testing Accuracy: 0.77

Weighted Precision: 0.77
Weighted Recall: 0.77
Weighted F1-score: 0.77

Classification Report

              precision    recall  f1-score   support

     Class 1       0.74      0.78      0.76       281
     Class 2       0.80      0.76      0.78       319

    accuracy                           0.77       600
   macro avg       0.77      0.77      0.77       600
weighted avg       0.77      0.77      0.77       600



# KNN

In [235]:
# knn
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
import pickle
model_knn = KNeighborsClassifier(n_neighbors=1)
filename = 'model_knn.sav'
pickle.dump(kmeans, open(filename, 'wb'))
model_knn1 =model_knn.fit(x_train, y_train)
y_pred_knn = model_knn1.predict(x_test)
print("KNN Results")
print("KNN Accuracy: ",accuracy_score(y_test, y_pred_knn)*100,"%")

KNN Results
KNN Accuracy:  74.33333333333333 %


In [236]:
#print(y_pred1)
print("KNN Results")
#print('\nTraining Accuracy: {:.2f}\n'.format(accuracy_score(y_train, y_pred1)))
print('\nTesting Accuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred_knn)))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred_knn, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred_knn, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred_knn, average='weighted')))

print('\nClassification Report\n')
print(classification_report(y_test, y_pred_knn, target_names=['Class 1', 'Class 2']))

KNN Results

Testing Accuracy: 0.74

Weighted Precision: 0.74
Weighted Recall: 0.74
Weighted F1-score: 0.74

Classification Report

              precision    recall  f1-score   support

     Class 1       0.72      0.75      0.73       281
     Class 2       0.77      0.74      0.75       319

    accuracy                           0.74       600
   macro avg       0.74      0.74      0.74       600
weighted avg       0.74      0.74      0.74       600



# Logistic regression

In [237]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report

In [238]:
Classifier_LOG_REG = LogisticRegression()

Model_LOG_REG=Classifier_LOG_REG.fit(x_train, y_train)

filename = 'Model_LOG_REG.sav'
pickle.dump(Model_LOG_REG, open(filename, 'wb'))

predictions = Model_LOG_REG.predict(x_test)
print(f"Test Set Accuracy : {accuracy_score(y_test, predictions) * 100} %\n\n")

Test Set Accuracy : 70.33333333333334 %


