# Importing libraries

In [84]:
import numpy as np
import pandas as pd
import os
import csv
import cv2
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score

In [85]:
!pip install opencv-python

# Path of positive and negative images

In [86]:
folder1=r"C:\ICTS\ICTS DATASET\Positive images\SideRoadLeft2"
folder2=r"C:\ICTS\ICTS DATASET\Negative_3000"

# Data Pre-processing

# SIFT descriptor

# Class : SideRoadLeft

In [87]:
i=0
for filename in os.listdir(folder1):
    #path
    try:
        path=os.path.join(folder1,filename)
        a=cv2.imread(path)

        #resize image
        resize=(180,230)
        img=cv2.resize(a,resize)
    except Exception as e:
        print(str(e))
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv(r'C:\ICTS\ICTS DATASET\pp1k.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (424, 128)
descriptor shape  1  :  (314, 128)
descriptor shape  2  :  (304, 128)
descriptor shape  3  :  (383, 128)
descriptor shape  4  :  (335, 128)
descriptor shape  5  :  (321, 128)
descriptor shape  6  :  (309, 128)
descriptor shape  7  :  (273, 128)
descriptor shape  8  :  (276, 128)
descriptor shape  9  :  (277, 128)
descriptor shape  10  :  (278, 128)
descriptor shape  11  :  (229, 128)
descriptor shape  12  :  (298, 128)
descriptor shape  13  :  (253, 128)
descriptor shape  14  :  (249, 128)
descriptor shape  15  :  (277, 128)
descriptor shape  16  :  (233, 128)
descriptor shape  17  :  (238, 128)
descriptor shape  18  :  (202, 128)
descriptor shape  19  :  (202, 128)
descriptor shape  20  :  (244, 128)
descriptor shape  21  :  (188, 128)
descriptor shape  22  :  (196, 128)
descriptor shape  23  :  (342, 128)
descriptor shape  24  :  (177, 128)
descriptor shape  25  :  (214, 128)
descriptor shape  26  :  (221, 128)
descriptor shape  27  :  (232, 128)
de

In [88]:
data1 = pd.read_csv(r'C:\ICTS\ICTS DATASET\pp1k.csv',header=None,dtype='uint8')
#MemoryError: Unable to allocate 166. MiB for an array with shape (128, 169606) and data type float64,
#Double-precision floating-point format

data1=data1.astype(np.uint8) 
#as unit8 contain 1 byte(8bit) and ranges from 0 to 255
data1

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0        86    9    3    9   12    5   16   89    3    1  ...   99   22    2   
1         0    0    0    0    0    0    0    0    0   12  ...    1   20  109   
2         0    0    6   34    3    0    0    0    3   67  ...    8  132    8   
3        35   28   21   15   12    6    6    8   39   30  ...    7    1   95   
4        26   26   21   22   76   17    7    6   74   84  ...    0    7    0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
792991    7    0    0  115  138    2    1   22   52    2  ...    2   99   29   
792992    0    1    2    1    0    0    0    0   31   14  ...    0    7   88   
792993    0    0    0    1   77   71    3    2   40   10  ...    5   14   21   
792994    7    4    2    2    0    0    0    1   23    7  ...    0   37   48   
792995    0    0    0    0    0    0    0    0  125    2  ...    0    0    8   

        121  122  123  124  125  126  127  
0         0    0    0    0   20   20   16  
1        11   24   43    0    1   13  129  
2         7   42  133   31    0    0    2  
3        29   50   30    9    8   31   61  
4         0    0    0    0    0    0    0  
...     ...  ...  ...  ...  ...  ...  ...  
792991   23    5    0    1    1    2   14  
792992   18    1    4    6    2    6  105  
792993    1    0    2    8    3    2   12  
792994   33   16    5    0    0    0   12  
792995  139  111    0    0    1    1    0  

[792996 rows x 128 columns]

# Negative Images

In [89]:
i=0
for filename in os.listdir(folder2):
    try:
        path=os.path.join(folder2,filename)
        a=cv2.imread(path)

        #resize image
        resize=(180,230)
        img=cv2.resize(a,resize)
    except Exception as e:
        print(str(e))
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv(r'C:\ICTS\ICTS DATASET\pn1k.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (109, 128)
descriptor shape  1  :  (123, 128)
descriptor shape  2  :  (120, 128)
descriptor shape  3  :  (118, 128)
descriptor shape  4  :  (194, 128)
descriptor shape  5  :  (202, 128)
descriptor shape  6  :  (189, 128)
descriptor shape  7  :  (182, 128)
descriptor shape  8  :  (139, 128)
descriptor shape  9  :  (94, 128)
descriptor shape  10  :  (93, 128)
descriptor shape  11  :  (81, 128)
descriptor shape  12  :  (85, 128)
descriptor shape  13  :  (185, 128)
descriptor shape  14  :  (115, 128)
descriptor shape  15  :  (108, 128)
descriptor shape  16  :  (112, 128)
descriptor shape  17  :  (100, 128)
descriptor shape  18  :  (107, 128)
descriptor shape  19  :  (140, 128)
descriptor shape  20  :  (142, 128)
descriptor shape  21  :  (112, 128)
descriptor shape  22  :  (88, 128)
descriptor shape  23  :  (122, 128)
descriptor shape  24  :  (223, 128)
descriptor shape  25  :  (98, 128)
descriptor shape  26  :  (131, 128)
descriptor shape  27  :  (110, 128)
descript

In [91]:
data2= pd.read_csv(r'C:\ICTS\ICTS DATASET\pn1k.csv',header=None,dtype='uint8')
data2=data2.astype(np.uint8)
data2

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0        45   26    8    1    0    0    0    2  182   33  ...    0    2    0   
1        23    0    0    1    4    2    0   11  153    0  ...    1    8    2   
2        71    5    0    0    0    1    1    7  153   21  ...    0    0    1   
3        25   33   26   47   15    0    0    0  148  110  ...    0   40  107   
4       135   77    7    4    0    1    4   11   83   61  ...    0   34   31   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
692114    7    0    0    0    7    7    3    8  110    9  ...    0    0  112   
692115   24    3    0    0    1    0    0    6  125   60  ...   23   12   26   
692116   41    2    0    0    0    0    0    1  214   12  ...    7   32    6   
692117   79   68    0    0    0    0    0    0  154   56  ...    0    0    0   
692118   28    5    0    0    6   13   34   75   58   32  ...   23  134   14   

        121  122  123  124  125  126  127  
0         0    0    0    0    0    0    0  
1         4    2    9   20    0    0    0  
2         2    0    4   84    3    0    0  
3         0    0    1   11    2    1   35  
4         0    0    5    7    0    0   20  
...     ...  ...  ...  ...  ...  ...  ...  
692114   20    5   12   64    6    1   10  
692115   33    3    2    3   30   22    4  
692116    1    0    2    5    0    5   13  
692117    0    2   24   21    0    0    0  
692118    0    0   41   38    1    6  117  

[692119 rows x 128 columns]

# Appending all data

In [92]:
data=data1.append(data2)

In [93]:
csv_data=data.to_csv(r'C:\ICTS\ICTS DATASET\Sift_Finalp1k.csv', mode='a', header=False,index=False)

In [94]:
data

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0        86    9    3    9   12    5   16   89    3    1  ...   99   22    2   
1         0    0    0    0    0    0    0    0    0   12  ...    1   20  109   
2         0    0    6   34    3    0    0    0    3   67  ...    8  132    8   
3        35   28   21   15   12    6    6    8   39   30  ...    7    1   95   
4        26   26   21   22   76   17    7    6   74   84  ...    0    7    0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
692114    7    0    0    0    7    7    3    8  110    9  ...    0    0  112   
692115   24    3    0    0    1    0    0    6  125   60  ...   23   12   26   
692116   41    2    0    0    0    0    0    1  214   12  ...    7   32    6   
692117   79   68    0    0    0    0    0    0  154   56  ...    0    0    0   
692118   28    5    0    0    6   13   34   75   58   32  ...   23  134   14   

        121  122  123  124  125  126  127  
0         0    0    0    0   20   20   16  
1        11   24   43    0    1   13  129  
2         7   42  133   31    0    0    2  
3        29   50   30    9    8   31   61  
4         0    0    0    0    0    0    0  
...     ...  ...  ...  ...  ...  ...  ...  
692114   20    5   12   64    6    1   10  
692115   33    3    2    3   30   22    4  
692116    1    0    2    5    0    5   13  
692117    0    2   24   21    0    0    0  
692118    0    0   41   38    1    6  117  

[1485115 rows x 128 columns]

# K means clustering

In [95]:
kmeans = KMeans(n_clusters=5)
kmeans.fit(data)
import pickle
# save the model to disk
filename = 'Kmeans_CL_5_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [96]:
hist=np.histogram(kmeans.labels_,bins=[0,1,2,3,4,5])


print('histogram of trained kmeans')
print(hist,"\n")

histogram of trained kmeans
(array([213814, 205996, 307469, 317735, 440101], dtype=int64), array([0, 1, 2, 3, 4, 5])) 



# K means prediction for SideRoadLeft class

In [97]:
#performing kmeans prediction of the entire Staircase dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder1):
    try:
        #path
        path=os.path.join(folder1,filename)
        a=cv2.imread(path)

        #resize image
        resize=(280,430)
        img=cv2.resize(a,resize)
    except Exception as e:
        print(str(e))
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans.predict(array_double)
    
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv(r'C:\ICTS\ICTS DATASET\FinalStrp1k.csv', mode='a',header=False,index=False)

# K means prediction for negative images

In [98]:
#performing kmeans prediction of the entire Non_Staircase dataset with the pretrained kmeans model

#initialising i=1; as its the 2nd class
i=1
data=[]
k=0
for filename in os.listdir(folder2):
    try:
        path=os.path.join(folder2,filename)
        a=cv2.imread(path)
        resize=(280,430)
        img=cv2.resize(a,resize)
    except Exception as e:
        print(str(e))
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    sift = cv2.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float' but got 'double', in order to avoid this dtype=np.double
    try:
        array_double = np.array(out, dtype=np.double)
        a=kmeans.predict(array_double)
    except ValueError as v:
        pass
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv(r'C:\ICTS\ICTS DATASET\FinalNstrp1k.csv', mode='a',header=False,index=False)

# Predicted data (SideRoadLeft)

In [99]:
#Displaying the kmeans predicted data
print("SideRoadLeft")
dat1= pd.read_csv(r'C:\ICTS\ICTS DATASET\FinalStrp1k.csv',header=None)
print(dat1)

SideRoadLeft
        0    1    2    3    4  5
0     153  159  126  277  333  0
1     123  100  155  174  240  0
2     117  155  115  258  376  0
3     184  179  152  193  271  0
4     163  180  171  115  209  0
...   ...  ...  ...  ...  ... ..
2995  246  201  166  191  319  0
2996  296  225  122  212  350  0
2997  325  272  108  205  350  0
2998  440  412  115  268  407  0
2999  168  161  138  279  343  0

[3000 rows x 6 columns]


# Predicted data (Negative images)

In [100]:
print("Non-SideRoadLeft")
dat2= pd.read_csv(r'C:\ICTS\ICTS DATASET\FinalNstrp1k.csv',header=None)
print(dat2)

Non-SideRoadLeft
       0   1    2   3    4  5
0     43  53   44  54   41  1
1     75  89   87  99  130  1
2     57  40   94  41   33  1
3     53  50  128  28   21  1
4     71  70  172  75   86  1
...   ..  ..  ...  ..  ... ..
2995  17  18  111  15   18  1
2996  50  37  137  21   38  1
2997  39  38  125  31   28  1
2998  39  35  117  17   21  1
2999  47  35  149  13   11  1

[3000 rows x 6 columns]


In [101]:
#appending All classes into 1 csv file

A=dat1.append(dat2)

csv_data=A.to_csv('C:\ICTS\ICTS DATASET\FinalFVp1k.csv', mode='a',header=False,index=False)

In [102]:
A

0    1    2    3    4  5
0     153  159  126  277  333  0
1     123  100  155  174  240  0
2     117  155  115  258  376  0
3     184  179  152  193  271  0
4     163  180  171  115  209  0
...   ...  ...  ...  ...  ... ..
2995   17   18  111   15   18  1
2996   50   37  137   21   38  1
2997   39   38  125   31   28  1
2998   39   35  117   17   21  1
2999   47   35  149   13   11  1

[6000 rows x 6 columns]

In [103]:
x = A.iloc[:,0:5].values

In [104]:
x

array([[153, 159, 126, 277, 333],
       [123, 100, 155, 174, 240],
       [117, 155, 115, 258, 376],
       ...,
       [ 39,  38, 125,  31,  28],
       [ 39,  35, 117,  17,  21],
       [ 47,  35, 149,  13,  11]], dtype=int64)

In [105]:
y = A.iloc[:,5].values

In [106]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

# Using StandardScaler

In [107]:
from sklearn.preprocessing import StandardScaler
DhoniS = StandardScaler()
Dhoni = DhoniS.fit_transform(x)

In [108]:
Dhoni

array([[ 0.62352246,  0.78151935, -0.1100231 ,  1.43024978,  1.19194328],
       [ 0.17831888, -0.11917687,  0.51402813,  0.34052626,  0.42584319],
       [ 0.08927816,  0.7204552 , -0.34673219,  1.22923282,  1.5461616 ],
       ...,
       [-1.06825116, -1.0656712 , -0.13154211, -1.17239087, -1.32053551],
       [-1.06825116, -1.11146931, -0.30369417, -1.32050863, -1.37819896],
       [-0.9495302 , -1.11146931,  0.38491408, -1.36282799, -1.46057531]])

# Principal Component Analysis

In [109]:
from sklearn.decomposition import PCA

In [110]:
pca = PCA(n_components=None)
pca.fit(Dhoni)

PCA()

In [111]:
Bhumi = pca.transform(Dhoni)

In [112]:
Bhumi

array([[ 1.92600279e+00, -7.93825891e-01, -3.23438981e-01,
         1.70186088e-01,  6.91281100e-02],
       [ 5.13357884e-01,  1.99161311e-01, -5.00689675e-01,
        -2.28801702e-01,  3.58371673e-02],
       [ 1.65705314e+00, -1.11882276e+00, -5.35122429e-01,
         2.19604077e-01, -4.65518065e-01],
       ...,
       [-2.28200003e+00,  4.44630345e-01,  1.39439749e-03,
         5.02558711e-02,  6.84505347e-02],
       [-2.44132894e+00,  3.59879739e-01,  1.43965160e-01,
        -6.85969165e-03,  3.94545676e-02],
       [-2.28792910e+00,  1.01132228e+00, -6.03300609e-02,
        -6.16708773e-02,  1.04285793e-01]])

In [113]:
Bhumi = pd.DataFrame(Bhumi)

In [114]:
Bhumi

0         1         2         3         4
0     1.926003 -0.793826 -0.323439  0.170186  0.069128
1     0.513358  0.199161 -0.500690 -0.228802  0.035837
2     1.657053 -1.118823 -0.535122  0.219604 -0.465518
3     1.761955  0.256893  0.377687 -0.017182 -0.035450
4     1.069214  1.019957  0.598815  0.073673 -0.330513
...        ...       ...       ...       ...       ...
5995 -2.782063  0.189482 -0.065597  0.018792 -0.004843
5996 -2.160360  0.697383 -0.021193 -0.124935  0.027717
5997 -2.282000  0.444630  0.001394  0.050256  0.068451
5998 -2.441329  0.359880  0.143965 -0.006860  0.039455
5999 -2.287929  1.011322 -0.060330 -0.061671  0.104286

[6000 rows x 5 columns]

In [115]:
Bhumi.shape

(6000, 5)

In [116]:
print(pca.explained_variance_ratio_) 

[0.68473909 0.19553623 0.09546339 0.0163635  0.00789779]


In [117]:
pca = PCA(n_components=3)
pca.fit(Dhoni)

PCA(n_components=3)

In [118]:
# save the model to disk
filename = 'PCA_3_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [119]:
Bhumi = pca.transform(Dhoni)

In [120]:
Bhumi

array([[ 1.92600279e+00, -7.93825891e-01, -3.23438981e-01],
       [ 5.13357884e-01,  1.99161311e-01, -5.00689675e-01],
       [ 1.65705314e+00, -1.11882276e+00, -5.35122429e-01],
       ...,
       [-2.28200003e+00,  4.44630345e-01,  1.39439749e-03],
       [-2.44132894e+00,  3.59879739e-01,  1.43965160e-01],
       [-2.28792910e+00,  1.01132228e+00, -6.03300609e-02]])

In [121]:
Bhumi.shape

(6000, 3)

In [122]:
print(pca.explained_variance_ratio_) 

[0.68473909 0.19553623 0.09546339]


In [123]:
Bhumi = pd.DataFrame(Bhumi)

In [124]:
Bhumi

0         1         2
0     1.926003 -0.793826 -0.323439
1     0.513358  0.199161 -0.500690
2     1.657053 -1.118823 -0.535122
3     1.761955  0.256893  0.377687
4     1.069214  1.019957  0.598815
...        ...       ...       ...
5995 -2.782063  0.189482 -0.065597
5996 -2.160360  0.697383 -0.021193
5997 -2.282000  0.444630  0.001394
5998 -2.441329  0.359880  0.143965
5999 -2.287929  1.011322 -0.060330

[6000 rows x 3 columns]

In [125]:
B=pd.concat([Bhumi, pd.DataFrame(y)],axis=1)

In [126]:
B

0         1         2  0
0     1.926003 -0.793826 -0.323439  0
1     0.513358  0.199161 -0.500690  0
2     1.657053 -1.118823 -0.535122  0
3     1.761955  0.256893  0.377687  0
4     1.069214  1.019957  0.598815  0
...        ...       ...       ... ..
5995 -2.782063  0.189482 -0.065597  1
5996 -2.160360  0.697383 -0.021193  1
5997 -2.282000  0.444630  0.001394  1
5998 -2.441329  0.359880  0.143965  1
5999 -2.287929  1.011322 -0.060330  1

[6000 rows x 4 columns]

In [127]:
csv_data=B.to_csv('C:\ICTS\ICTS DATASET\FinalPCAFVp1k.csv', mode='a',header=False,index=False)

# Training , Testing and Classification

In [128]:
data= pd.read_csv(r'C:\ICTS\ICTS DATASET\FinalPCAFVp1k.csv',header=None)

data

0         1         2  3
0     1.926003 -0.793826 -0.323439  0
1     0.513358  0.199161 -0.500690  0
2     1.657053 -1.118823 -0.535122  0
3     1.761955  0.256893  0.377687  0
4     1.069214  1.019957  0.598815  0
...        ...       ...       ... ..
5995 -2.782063  0.189482 -0.065597  1
5996 -2.160360  0.697383 -0.021193  1
5997 -2.282000  0.444630  0.001394  1
5998 -2.441329  0.359880  0.143965  1
5999 -2.287929  1.011322 -0.060330  1

[6000 rows x 4 columns]

In [129]:
#assigning x the columns from 1 to 128 for training
x = data.iloc[:,0:3].values
print("X values")
print(x)

#assigning y with the column "Class" as target variable
y = data.iloc[:,3]
print("Y values")
print(y)

X values
[[ 1.92600279e+00 -7.93825891e-01 -3.23438981e-01]
 [ 5.13357884e-01  1.99161311e-01 -5.00689675e-01]
 [ 1.65705314e+00 -1.11882276e+00 -5.35122429e-01]
 ...
 [-2.28200003e+00  4.44630345e-01  1.39439749e-03]
 [-2.44132894e+00  3.59879739e-01  1.43965160e-01]
 [-2.28792910e+00  1.01132228e+00 -6.03300609e-02]]
Y values
0       0
1       0
2       0
3       0
4       0
       ..
5995    1
5996    1
5997    1
5998    1
5999    1
Name: 3, Length: 6000, dtype: int64


In [130]:
#Dataset split into train and test with 80% Training and 20% Testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.10, random_state=0)

# Decision Tree

In [131]:
#Decision Tree Classifier
from sklearn.metrics import accuracy_score
#Assign model with Decision Tree classifier
model1 = DecisionTreeClassifier(max_depth=13)
filename = 'model1.sav'
pickle.dump(kmeans, open(filename, 'wb'))
#training the model with the Training Variables 
model1.fit(x_train, y_train)
#predicting the traget variable using testing variables
y_pred1 = model1.predict(x_test)

#Results
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred1))
print("Decision Tree Results")
print("Decision Tree Accuracy: ",accuracy_score(y_test, y_pred1)*100,"%")

print("Decision Tree Results")
# print('\nTraining Accuracy: {:.2f}\n'.format(accuracy_score(y_train, y_pred1)))
print('\nTesting Accuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred1)))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred1, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred1, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred1, average='weighted')))

print('\nClassification Report\n')
print(classification_report(y_test, y_pred1, target_names=['Class 1', 'Class 2']))

[[223  58]
 [ 96 223]]
Decision Tree Results
Decision Tree Accuracy:  74.33333333333333 %
Decision Tree Results

Testing Accuracy: 0.74

Weighted Precision: 0.75
Weighted Recall: 0.74
Weighted F1-score: 0.74

Classification Report

              precision    recall  f1-score   support

     Class 1       0.70      0.79      0.74       281
     Class 2       0.79      0.70      0.74       319

    accuracy                           0.74       600
   macro avg       0.75      0.75      0.74       600
weighted avg       0.75      0.74      0.74       600



In [132]:
#Recognition &Validation
#Assigning path with any any class image
data=[]
path=r"C:\ICTS\ICTS DATASET\Positive images\SideRoadLeft2\sideroadleft44.jpg"


#Repeated the process of image pre-processing and feature extraction
try:
    a=cv2.imread(path)
    resize=(280,430)

    #resize image
    img=cv2.resize(a,resize)
except Exception as e:
    print("corrupt Img")
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

#initialise sift descriptor
sift = cv2.SIFT_create()
keypoints, descriptors = sift.detectAndCompute(gray, None)

#convert the descriptor array into a dataframe format
out=pd.DataFrame(descriptors)
print("Descriptor Shape:",out.shape)

#initialise Kmeans and create 5 clusters


#train the model for the features i.e. for all elements in the Dataframe
array_double = np.array(out, dtype=np.double)
a=kmeans.predict(array_double)

#get the values of the histogram for one image only for 5 clusters i.e. in 5 bins
#kmeans.labels_ give us the label vlaue of the feature that its clustered into
#hist will give the hostogram for all those vlaues
hist=np.histogram(a,bins=[0,1,2,3,4,5])

#append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
data.append(hist[0])

Output = pd.DataFrame(data)
print("Histogram:\n",Output)

Descriptor Shape: (816, 128)
Histogram:
      0    1    2    3    4
0  133  123  136  152  272


In [133]:
from sklearn.preprocessing import StandardScaler
MuktaS = StandardScaler()
Mukta = MuktaS.fit_transform(Output)

In [134]:
Mukta

array([[0., 0., 0., 0., 0.]])

In [135]:
Mukta.shape

(1, 5)

In [136]:
MB = pca.transform(Mukta)

In [137]:
MB.shape

(1, 3)

In [138]:
MB

array([[ 7.03867963e-17, -1.84419845e-16, -2.26123976e-17]])

In [139]:
#prediction
y_pred1 = model1.predict(MB)

#prints the prediction of the class
print(y_pred1)

[0]


# SVC

In [140]:
from sklearn.svm import SVC
DhoniSVM_LK = SVC(kernel='rbf')
Dhoni_LK = DhoniSVM_LK.fit(x_train, y_train)

In [141]:
filename = 'SVC_RBF_PCA_3.sav'
pickle.dump(Dhoni_LK, open(filename, 'wb'))

In [142]:
Dhoni_LK

SVC()

In [143]:
y_pred_LK = Dhoni_LK.predict(x_test)

In [144]:
y_pred_LK

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,

In [145]:
from sklearn.metrics import confusion_matrix

In [146]:
confusion_matrix(y_test, y_pred_LK)

array([[230,  51],
       [ 92, 227]], dtype=int64)

In [147]:
from sklearn.metrics import accuracy_score

In [148]:
accuracy_score(y_test, y_pred_LK)

0.7616666666666667

In [149]:
y_pred1 = model1.predict(MB)



In [164]:
#print(y_pred1)
print("SVC Results")
#print('\nTraining Accuracy: {:.2f}\n'.format(accuracy_score(y_train, y_pred_LK)))
print('\nTesting Accuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred_LK)))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred_LK, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred_LK, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred_LK, average='weighted')))

print('\nClassification Report\n')
print(classification_report(y_test, y_pred_LK, target_names=['Class 1', 'Class 2']))

SVC Results

Testing Accuracy: 0.76

Weighted Precision: 0.77
Weighted Recall: 0.76
Weighted F1-score: 0.76

Classification Report

              precision    recall  f1-score   support

     Class 1       0.71      0.82      0.76       281
     Class 2       0.82      0.71      0.76       319

    accuracy                           0.76       600
   macro avg       0.77      0.77      0.76       600
weighted avg       0.77      0.76      0.76       600



# Random Forest 

In [151]:
#Random Forest Classifier
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
import pickle
model_rf = RandomForestClassifier(n_estimators = 500)
filename = 'model_rf.sav'
pickle.dump(kmeans, open(filename, 'wb'))
model_rf1 =model_rf.fit(x_train, y_train)
y_pred_rf = model_rf1.predict(x_test)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred_rf)
print("Random Forest Accuracy: ",accuracy_score(y_test, y_pred_rf)*100,"%")

Random Forest Accuracy:  77.66666666666666 %


In [160]:
#print(y_pred1)
print("Random Forest Results")
#print('\nTraining Accuracy: {:.2f}\n'.format(accuracy_score(y_train, y_pred1)))
print('\nTesting Accuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred_rf)))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred_rf, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred_rf, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred_rf, average='weighted')))

print('\nClassification Report\n')
print(classification_report(y_test, y_pred_rf, target_names=['Class 1', 'Class 2']))

Random Forest Results

Testing Accuracy: 0.78

Weighted Precision: 0.78
Weighted Recall: 0.78
Weighted F1-score: 0.78

Classification Report

              precision    recall  f1-score   support

     Class 1       0.74      0.81      0.77       281
     Class 2       0.82      0.75      0.78       319

    accuracy                           0.78       600
   macro avg       0.78      0.78      0.78       600
weighted avg       0.78      0.78      0.78       600



# SVM

In [153]:
# SVM
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
import pickle
SVM_LK = SVC(kernel='rbf')
LK = SVM_LK.fit(x_train, y_train)
filename = 'SVC_RBF_PCA_3.sav'
pickle.dump(LK, open(filename, 'wb'))
y_pred_LK = LK.predict(x_test)
print(accuracy_score(y_test, y_pred_LK))

0.7616666666666667


In [154]:
#print(y_pred1)
print("SVM Results")
#print('\nTraining Accuracy: {:.2f}\n'.format(accuracy_score(y_train, y_pred1)))
print('\nTesting Accuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred_LK)))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred_LK, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred_LK, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred_LK, average='weighted')))

print('\nClassification Report\n')
print(classification_report(y_test, y_pred_LK, target_names=['Class 1', 'Class 2']))

SVM Results

Testing Accuracy: 0.76

Weighted Precision: 0.77
Weighted Recall: 0.76
Weighted F1-score: 0.76

Classification Report

              precision    recall  f1-score   support

     Class 1       0.71      0.82      0.76       281
     Class 2       0.82      0.71      0.76       319

    accuracy                           0.76       600
   macro avg       0.77      0.77      0.76       600
weighted avg       0.77      0.76      0.76       600



# KNN

In [155]:
# knn
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
import pickle
model_knn = KNeighborsClassifier(n_neighbors=1)
filename = 'model_knn.sav'
pickle.dump(kmeans, open(filename, 'wb'))
model_knn1 =model_knn.fit(x_train, y_train)
y_pred_knn = model_knn1.predict(x_test)
print("KNN Results")
print("KNN Accuracy: ",accuracy_score(y_test, y_pred_knn)*100,"%")

KNN Results
KNN Accuracy:  71.33333333333334 %


In [156]:
#print(y_pred1)
print("KNN Results")
#print('\nTraining Accuracy: {:.2f}\n'.format(accuracy_score(y_train, y_pred1)))
print('\nTesting Accuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred_knn)))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred_knn, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred_knn, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred_knn, average='weighted')))

print('\nClassification Report\n')
print(classification_report(y_test, y_pred_knn, target_names=['Class 1', 'Class 2']))

KNN Results

Testing Accuracy: 0.71

Weighted Precision: 0.71
Weighted Recall: 0.71
Weighted F1-score: 0.71

Classification Report

              precision    recall  f1-score   support

     Class 1       0.70      0.69      0.69       281
     Class 2       0.73      0.73      0.73       319

    accuracy                           0.71       600
   macro avg       0.71      0.71      0.71       600
weighted avg       0.71      0.71      0.71       600



# Logistic regression

In [157]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report

In [158]:
Classifier_LOG_REG = LogisticRegression()

Model_LOG_REG=Classifier_LOG_REG.fit(x_train, y_train)

filename = 'Model_LOG_REG.sav'
pickle.dump(Model_LOG_REG, open(filename, 'wb'))

predictions = Model_LOG_REG.predict(x_test)
print(f"Test Set Accuracy : {accuracy_score(y_test, predictions) * 100} %\n\n")

Test Set Accuracy : 69.83333333333334 %


